terasolunaorg/terasoluna-gfw-functionaltest

terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-domain/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-domain.xml, terasoluna-gfw-functionaltest-env/configs/resin-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/resin-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/weblogic-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/date/DateController.java
Please review #162  , and merge to master branch.
=> Apply Separate joda-Time #162

terasoluna-gfw-functionaltest-env/configs/weblogic-oracle/resources/META-INF/services/javax.persistence.spi.PersistenceProvider, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/weblogic.xml
Please review #166 ,and merge to master branch.
=> Modified weblogic.xml and Add file that specified jpa Provider #166

terasoluna-gfw-functionaltest-env/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-infra-mybatis2/src/main/java/org/terasoluna/gfw/functionaltest/infra/repository/queryescape/DatabaseMetaInfoServiceMybatis2Impl.java, terasoluna-gfw-functionaltest-infra-mybatis2/src/main/java/org/terasoluna/gfw/functionaltest/infra/repository/queryescape/TodoMybatis2RepositoryImpl.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/queryescape/QueryEscapeTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/queryescape/QueryEscapeController.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/queryescape/QueryEscapeHelper.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/queryescape/QueryEscapeJpaWithFullWidthController.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/queryescape/QueryEscapeMybatisWithFullWidthController.java, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/queryescape/index.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/queryescape/queryescape/todoListWithFullWidth.jsp
backported manually #164 
please review
=> support escaping full-width wildcard in like query #164

terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-infra-mybatis2/pom.xml, terasoluna-gfw-functionaltest-infra-mybatis3/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-parent/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> reversion 1.1.0 -> 5.0.0 #169

terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/service/codelist/CodeListServiceImpl.java, terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/service/redirect/RedirectServiceImpl.java, terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-infra-mybatis2/src/main/java/org/terasoluna/gfw/functionaltest/infra/repository/queryescape/DatabaseMetaInfoServiceMybatis2Impl.java, terasoluna-gfw-functionaltest-infra-mybatis3/src/main/java/org/terasoluna/gfw/functionaltest/infra/repository/queryescape/DatabaseMetaInfoServiceMybatis3Impl.java
Please review #174 ,and merge to master branch.
=> Workaround for SPR-12577 #174

terasoluna-gfw-functionaltest-domain/src/main/resources/ValidationMessages.properties
Please review #177 ,and merge to master branch.
=> Added ValidationMessages.properties #177

terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-infra-mybatis2/pom.xml, terasoluna-gfw-functionaltest-infra-mybatis3/pom.xml, terasoluna-gfw-functionaltest-parent/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
Please review #186 ,and merge to master branch.
=> Setted scope #186

terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-infra-mybatis2/pom.xml, terasoluna-gfw-functionaltest-infra-mybatis3/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-parent/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> Change framework name #188

terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-infra-mybatis2/pom.xml, terasoluna-gfw-functionaltest-infra-mybatis3/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-parent/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> Upgrade Version to 5.1.0-SNAPSHOT. #190

terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-infra-mybatis2/pom.xml, terasoluna-gfw-functionaltest-infra-mybatis3/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-parent/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> Upgrade Version to 5.0.1-SNAPSHOT. #191

terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-infra-mybatis2/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-parent/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> Upgrade Version to 1.0.3-SNAPSHOT. #192

terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-infra.properties, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/resources/META-INF/web-fragment.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/resources/log4jdbc.properties, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/resources/logback-ddl.sql, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/resources/logback.xml
=> Add new configuration for Tomcat 8 + Oracle. #199

terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codelist/CodeListController.java
change file name CodeListContoller. #202
=> change file name CodeListContoller. #202

terasoluna-gfw-functionaltest-env/configs/jboss-postgresql/ContainerConfigXML/terasoluna-gfw-functionaltest-postgresql-ds.xml, terasoluna-gfw-functionaltest-env/configs/jboss-postgresql/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/jboss-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/jboss-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-infra.properties, terasoluna-gfw-functionaltest-env/configs/jboss-postgresql/resources/META-INF/web-fragment.xml, terasoluna-gfw-functionaltest-env/configs/jboss-postgresql/resources/log4jdbc.properties, terasoluna-gfw-functionaltest-env/configs/jboss-postgresql/resources/logback-ddl.sql, terasoluna-gfw-functionaltest-env/configs/jboss-postgresql/resources/logback.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
Please review #200 ,and merge to master branch.
=> Adding JBoss and Postgresql environment #200

terasoluna-gfw-functionaltest-env/configs/jboss-postgresql/ContainerConfigXML/terasoluna-gfw-functionaltest-postgresql-ds.xml
Removing unnecessary datasource settings
Please review #200, and marge to master branch.
=> Removing unnecessary settings #200

terasoluna-gfw-functionaltest-domain/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-codelist.xml, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/codelist/CodeListTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codelist/CodeListController.java, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/10_01_form.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/index.jsp
=> Add CodeList test when exception occurs. #212

terasoluna-gfw-functionaltest-parent/pom.xml
=> Upgrade Spring framework to 4.2.0.RC1 #216

terasoluna-gfw-functionaltest-parent/pom.xml
=> Overridden xml-apis jar version to 1.4.01 #218

terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/logging/userIdMDCPutFilter.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/redirect/login.jsp
=> Modified default sec params names to match to latest Spring Specs #220

terasoluna-gfw-functionaltest-parent/pom.xml
Please review Issue #218
Changes done as per below comment-
https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/218#issuecomment-114759579
=> Reverting the WorkAround of XML-APIS done in Issue #218

terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-infra.properties, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/resources/META-INF/web-fragment.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/resources/log4jdbc.properties, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/resources/logback-ddl.sql, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/resources/logback.xml, terasoluna-gfw-functionaltest-env/pom.xml
Support Tomcat8+PostgreSQL #198 
(squashed #206)
=> Support Tomcat8+PostgreSQL #198

terasoluna-gfw-functionaltest-env/pom.xml
=> add maven profile for Tomcat 8 + Oracle #199

terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-infra-mybatis2/pom.xml, terasoluna-gfw-functionaltest-infra-mybatis3/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-parent/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> #196: Polishing pom files

terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-infra-mybatis2/pom.xml, terasoluna-gfw-functionaltest-infra-mybatis3/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-parent/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
(cherry picked from commit 80882b5e7a433f964993d1babcb376b6d408206d)
Please review #196 .
=> [5.0.x] #196: Polishing pom files

terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-infra.properties, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/resources/META-INF/web-fragment.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/resources/log4jdbc.properties, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/resources/logback-ddl.sql, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/resources/logback.xml, terasoluna-gfw-functionaltest-env/pom.xml
I've backported to 1.0.x by manually.
Please review #198 .
=> Support Tomcat8+PostgreSQL in 1.0.x #198

terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/csrf/CsrfController.java, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-security.xml
=> fix csrfTokenTest Application #91

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/el/ElTest.java, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/el/beanQueryOutput.jsp
* apply specification change for List field
* apply specification change for null field
* modify to use criteriaQuery attribute of t:pagination tag (fix wrong implementation)
* modify wrong assertions(conditions that find page link element)
I resolved failures in existing test cases for `f:query()`.
Please review #223 .
=> #223: modify existing test cases for f:query

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/el/ElTest.java, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/el/beanQueryOutput.jsp
I've backported to 5.0.x.
Please review #223 .
=> [5.0.x] #223: modify existing test cases for f:query

terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-parent/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> #246: Update to 1.0.4-SNAPSHOT

terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-parent/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> #247: Update to 5.0.2-SNAPSHOT

.travis.yml, terasoluna-gfw-functionaltest-parent/pom.xml
Please review #54 .
I've checked this changes at the forked repository. test result refer to [here](https://travis-ci.org/kazuki43zoo/terasoluna-gfw-functionaltest) .
Please enable travis-CI for this repository.
=> #54: Support travis-CI

.travis.yml, terasoluna-gfw-functionaltest-parent/pom.xml
(cherry picked from commit 153126f9fc07402e3c1a05b945ac754a1f56e99d)
Please review #54 .
=> [5.0.x] #54: Support travis-CI

.travis.yml, terasoluna-gfw-functionaltest-parent/pom.xml
(cherry picked from commit 153126f9fc07402e3c1a05b945ac754a1f56e99d)
Conflicts:
terasoluna-gfw-functionaltest-parent/pom.xml
Conflicts resolved by manually.
Please review #54 .
=> [1.0.x] #54: Support travis-CI

.travis.yml
=> #255: travis-ci migrate to container-based infrastructure

.travis.yml
=> [5.0.x] #255: travis-ci migrate to container-based infrastructure 

.travis.yml
=> [1.0.x] #255: travis-ci migrate to container-based infrastructure

.travis.yml, terasoluna-gfw-functionaltest-env/configs/travis/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-parent/pom.xml
Please review #262 .
Main changes are as follows:
* Add PostgreSQL setup procedure
* Add database initialization procedure(`init-db`)
* Change to create `env.jar` for `tomcat8-postgresql`
* Change to create war file which include `env.jar` and `context.xml` (Add `context.xml` for travis)
Thanks.
=> #262: Change to use the PostgreSQL on Travis-Ci testing

.travis.yml, terasoluna-gfw-functionaltest-env/configs/travis/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-parent/pom.xml
(cherry picked from commit 452371a1c5ff0805badfcaa16461faf4e5d0ddeb)
Please review #262 .
=> [5.0.x] #262: Change to use the PostgreSQL on Travis-Ci testing

.travis.yml, terasoluna-gfw-functionaltest-env/configs/travis/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-parent/pom.xml
(cherry picked from commit 452371a1c5ff0805badfcaa16461faf4e5d0ddeb)
Please review #262 .
=> [1.0.x] #262: Change to use the PostgreSQL on Travis-Ci testing

terasoluna-gfw-functionaltest-initdb/pom.xml
modified pom.xml file of the init-db project.
=> #250: ojdbc version update (modified pom.xml of init-db project)

terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/logging/userIdMDCPutFilter.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/redirect/login.jsp
Please review #271 .
This changes apply #220 for resolving some failed test cases.
**Note:**
However, i think test application should be polishing more for reflecting specification changes of Spring Security 4.
=> Apply specification change for default url and parameter names of Spring Security 4 #271

terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-security.xml, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/logging/userIdMDCPutFilter.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/redirect/login.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/redirect/withgoto/loginWithGoTo.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/redirect/withwhitelist/loginWithWhiteList.jsp
Please review this improvement for #271.
**Note:**
* Please review #272 at first.
* Base branch is work branch of #272.
=> Improve Spring Security settings to use default value as possible #271

terasoluna-gfw-functionaltest-env/configs/jboss-postgresql/ContainerConfigXML/terasoluna-gfw-functionaltest-postgresql-ds.xml, terasoluna-gfw-functionaltest-env/configs/jboss-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/travis/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/weblogic-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml
=> change data source name #106

terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml
=> Remove workaround for SPR-12577 #256

terasoluna-gfw-functionaltest-initdb/pom.xml
=> Remove onError option for sql-maven-plugin #286

terasoluna-gfw-functionaltest-parent/pom.xml
=> Update Tomcat 8.0.29 on Travis-CI #289

terasoluna-gfw-functionaltest-parent/pom.xml
(cherry picked from commit 08b8f7a497fde4a5a51cd418c79c0c8156085515)
Please review #289 .
=> [5.0.x] Update Tomcat 8.0.29 on Travis-CI #289

terasoluna-gfw-functionaltest-parent/pom.xml
(cherry picked from commit 08b8f7a497fde4a5a51cd418c79c0c8156085515)
Please review #289 .
=> [1.0.x] Update Tomcat 8.0.29 on Travis-CI #289

.travis.yml, terasoluna-gfw-functionaltest-parent/pom.xml
=> Update PostgreSQL 9.4 on Travis-CI #288

.travis.yml, terasoluna-gfw-functionaltest-parent/pom.xml
(cherry picked from commit 032618190572772dcb6da98334e1f0676c8ccf41)
Please review #288 .
=> [5.0.x] Update PostgreSQL 9.4 on Travis-CI #288

.travis.yml, terasoluna-gfw-functionaltest-parent/pom.xml
I've backported to 1.0.x, please review #288 .
=> [1.0.x] Update PostgreSQL 9.4 on Travis-CI #288

terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/web.xml
=> Add config to disable URL rewriting by default #270

terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/web.xml
(cherry picked from commit 5a40ddc8a7c1287def14b07cf8bde9d072b2f538)
Please review #270 .
=> [5.0.x] Add config to disable URL rewriting by default #270

terasoluna-gfw-functionaltest-initdb/pom.xml
(cherry picked from commit 0b2ada4fcfa276b5c8f0c948f7d8dc2af1883df5)
Please review #286 .
=> [5.0.x] Remove onError option for sql-maven-plugin #286

terasoluna-gfw-functionaltest-initdb/pom.xml
(cherry picked from commit 0b2ada4fcfa276b5c8f0c948f7d8dc2af1883df5)
Please review #286 .
=> [1.0.x] Remove onError option for sql-maven-plugin #286

terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml
(cherry picked from commit 377a695c2a646b8e656939e0a816e9109d3699ca)
Please review #256 .
=> [5.0.x] Remove workaround for SPR-12577 #256

terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/service/codelist/ExistInCodeListService.java, terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/service/codelist/ExistInCodeListServiceImpl.java, terasoluna-gfw-functionaltest-domain/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-codelist.xml, terasoluna-gfw-functionaltest-domain/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-domain.xml, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/codelist/CodeListTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codelist/CodeListController.java, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-common.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc.xml, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/08_08_form.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/index.jsp
Add test case for validating method parameter using @ExistInCodeList 
Please review #283 .
=> add testcase @ExistInCodeList #283

terasoluna-gfw-functionaltest-env/configs/jboss-postgresql/ContainerConfigXML/terasoluna-gfw-functionaltest-postgresql-ds.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
#303
added environment config template file
=> added environment config template file #303

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/validation/ValidationTest.java, terasoluna-gfw-functionaltest-web/pom.xml, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/validation/ValidationController.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/validation/ValidationForm.java, terasoluna-gfw-functionaltest-web/src/main/resources/ValidationMessages.properties, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/validation/bytemax.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/validation/bytemin.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/validation/compare.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/validation/index.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/welcome/index.jsp
Thanks you for review of https://github.com/terasolunaorg/terasoluna-gfw/issues/372.
I've also made their functional test cases .
Please review #280.
=> Add test of validation #280

terasoluna-gfw-functionaltest-parent/pom.xml
=> Update Tomcat 8.0.30 on Travis-CI #309

terasoluna-gfw-functionaltest-parent/pom.xml
(cherry picked from commit e1dad315b5db1796a0e427ac4a1e51e2b8576d4b)
Please review #309 .
=> [5.0.x] Update Tomcat 8.0.30 on Travis-CI #309

terasoluna-gfw-functionaltest-parent/pom.xml
(cherry picked from commit e1dad315b5db1796a0e427ac4a1e51e2b8576d4b)
Please review #309 .
=> [1.0.x] Update Tomcat 8.0.30 on Travis-CI #309

terasoluna-gfw-functionaltest-env/configs/jboss-postgresql/ContainerConfigXML/terasoluna-gfw-functionaltest-postgresql-ds.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml
#317
created environment config by replace config tool
=> created environment config by replace config tool

terasoluna-gfw-functionaltest-env/configs/resin-oracle/ContainerConfigXML/app-terasoluna-gfw-functionaltest-web.xml, terasoluna-gfw-functionaltest-env/configs/resin-oracle/ContainerConfigXML/app-terasoluna-gfw-functionaltest-web.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/resin-postgresql/ContainerConfigXML/app-terasoluna-gfw-functionaltest-web.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
#303 
#317 
manual cherry-pick
=> cherry pick replace tool 1.0.x

.travis.yml, terasoluna-gfw-functionaltest-parent/pom.xml
=> Modify to use parent configurations for cargo-maven2-plugin #327

.travis.yml, terasoluna-gfw-functionaltest-parent/pom.xml
(cherry picked from commit 3c9050abe49c1ae8b0421f523c998f24c1c66038)
Please review #327 .
=> [5.0.x] Modify to use parent configurations for cargo-maven2-plugin #327

.travis.yml, terasoluna-gfw-functionaltest-parent/pom.xml
I've backported to 1.0.x by manually.
Please review #327 .
=> [1.0.x] Modify to use parent configurations for cargo-maven2-plugin #327

terasoluna-gfw-functionaltest-env/configs/jboss-postgresql/ContainerConfigXML/terasoluna-gfw-functionaltest-postgresql-ds.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
cherry pick replace tool 5.0.x
#303 
#317
and change jndi name
=> cherry pick replace tool 5.0.x

terasoluna-gfw-functionaltest-env/configs/resin-oracle/ContainerConfigXML/app-terasoluna-gfw-functionaltest-web.xml, terasoluna-gfw-functionaltest-env/configs/resin-oracle/ContainerConfigXML/app-terasoluna-gfw-functionaltest-web.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/resin-postgresql/ContainerConfigXML/app-terasoluna-gfw-functionaltest-web.xml, terasoluna-gfw-functionaltest-env/configs/resin-postgresql/ContainerConfigXML/app-terasoluna-gfw-functionaltest-web.xml.env.ftl
#106
change jndi name on resin
=> change jndi name on resin

terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-security.xml
=> modify 'auto-config' configuration #333

terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
=> Fix connection pool settings(maxWaitMillis, maxTotal) for tomcat8 #331

terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
(cherry picked from commit 10ceea1d5332b0ed8a41fc816a25f9d681d8ba48)
Please review #331 .
=> [5.0.x] Fix connection pool settings(maxWaitMillis, maxTotal) for tomcat8 #331

terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl
=> [1.0.x] Fix connection pool settings(maxWaitMillis, maxTotal) for tomcat8 #331

terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/weblogic.xml
#342 
added com.fasterxml.jackson.* in weblogic.xml
=> added com.fasterxml.jackson.* in weblogic.xml

terasoluna-gfw-functionaltest-env/configs/weblogic-oracle/ContainerConfig/setWebLogicResources.py, terasoluna-gfw-functionaltest-env/configs/weblogic-oracle/ContainerConfig/setWebLogicResources.py.env.ftl
=> Create Weblogic Resources ScriptFile. #344

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/validation/ValidationTest.java, terasoluna-gfw-functionaltest-web/src/main/resources/ValidationMessages.properties
Please review and merge #346 .
=> improve validation messages #346

terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/weblogic.xml
#342
cherry-pick 1fbab1fe07a8aad191f7d7971230eed564ef80b3
=> add jackson weblogic xml 5.0.x

terasoluna-gfw-functionaltest-web/pom.xml
=> change dependency web to web-jsp. issues:#335

terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/ContainerConfigXML/context.xml.env.ftl
=> change oracle jdbc url #351

terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/ContainerConfigXML/context.xml.env.ftl
#351 
cherry-pick ff8c825e6553af681cc07861d7b1653d6138c2a7
=> change oracle jdbc url 5.0.x

terasoluna-gfw-functionaltest-env/configs/resin-oracle/ContainerConfigXML/app-terasoluna-gfw-functionaltest-web.xml, terasoluna-gfw-functionaltest-env/configs/resin-oracle/ContainerConfigXML/app-terasoluna-gfw-functionaltest-web.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml.env.ftl
=> change oracle jdbc url 1.0.x

terasoluna-gfw-functionaltest-env/configs/weblogic-oracle/ContainerConfig/setWebLogicResources.py, terasoluna-gfw-functionaltest-env/configs/weblogic-oracle/ContainerConfig/setWebLogicResources.py.env.ftl
=> Re-Create WebLogic Resouces ScriptFile. #344

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/transactiontoken/TransactionTokenTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/transactiontoken/TransactionTokenFlow7Controller.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/transactiontoken/TransactionTokenFunctionalTestController.java, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/flow1NamespaceStep2.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/flow1NamespaceStep3.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/flow1NamespaceStep4.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/flowAllNamespaceStep1.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/index.jsp
=> Add a test case of the namespace attribute @TransactionTokenCheck #306

terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/codepoints/CodepointsTest.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/codepoints/ConsistOfCheckTest.java, terasoluna-gfw-functionaltest-web/pom.xml, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codepoints/ConsistOfCheckController.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codepoints/ConsistOfCheckForm.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codepoints/HiraganaKatakanaChars.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codepoints/KanaChars.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codepoints/NumberChars.java, terasoluna-gfw-functionaltest-web/src/main/resources/ValidationMessages.properties, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codepoints/input.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codepoints/result.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/welcome/index.jsp
=> Add test cases for CodePoint. #275

terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/string/CustomFullHalf.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/string/FullHalfConverterTest.java
=> support-fullhalf testcase. #307

terasoluna-gfw-functionaltest-parent/pom.xml
#364
jdbc postgresql version up 9.4-1206-jdbc41
=> jdbc postgresql version up 9.4-1206-jdbc41

terasoluna-gfw-functionaltest-parent/pom.xml
#364
jdbc postgresql version up 9.4-1206-jdbc41
=> jdbc postgresql version up 9.4-1206-jdbc41 5.0.x

terasoluna-gfw-functionaltest-parent/pom.xml
#364
jdbc postgresql version up 9.4-1206-jdbc41
=> jdbc postgresql version up 9.4-1206-jdbc41 1.0.x

terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
=> Exclude org.hibernate in jboss-deployment-structure.xml. #368

terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
=> Exclude hibernate validator embedded in jboss  5.0.x #368

terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-domain/src/main/resources/META-INF/mybatis/mybatis-config.xml
=> [5.0.x] set proxy factory to cglib #371

terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-domain/src/main/resources/META-INF/mybatis/mybatis-config.xml
=> remove cglib dependency. issues:#371

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/codepoints/ConsistOfCheckTest.java, terasoluna-gfw-functionaltest-web/src/main/resources/ValidationMessages.properties
=> Issues/275 change code point based validation message #275

terasoluna-gfw-functionaltest-web/pom.xml
=> Change maven profile name (default -> local) #376

terasoluna-gfw-functionaltest-env/configs/webotx-oracle/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/webotx-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/webotx-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-infra.properties, terasoluna-gfw-functionaltest-env/configs/webotx-oracle/resources/META-INF/web-fragment.xml, terasoluna-gfw-functionaltest-env/configs/webotx-oracle/resources/log4jdbc.properties, terasoluna-gfw-functionaltest-env/configs/webotx-oracle/resources/logback-ddl.sql, terasoluna-gfw-functionaltest-env/configs/webotx-oracle/resources/logback.xml, terasoluna-gfw-functionaltest-env/configs/webotx-oracle/sh/jdbc-settings.sh, terasoluna-gfw-functionaltest-env/configs/webotx-oracle/sh/jdbc-settings.sh.env.ftl, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/nec-web.xml
=> Add WebOTX + Oracle #281

terasoluna-gfw-functionaltest-env/configs/interstage11-oracle/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/interstage11-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/interstage11-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-infra.properties, terasoluna-gfw-functionaltest-env/configs/interstage11-oracle/resources/META-INF/web-fragment.xml, terasoluna-gfw-functionaltest-env/configs/interstage11-oracle/resources/log4jdbc.properties, terasoluna-gfw-functionaltest-env/configs/interstage11-oracle/resources/logback-ddl.sql, terasoluna-gfw-functionaltest-env/configs/interstage11-oracle/resources/logback.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/glassfish-web.xml
@ikeyat , add interstage11 - oracle profile. please review.
=> Add Interstage - oracle profile. #339

terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
=> Excludes JBoss's logger.#380

terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
=> Excludes JBoss's logger.(5.0.x) #380

terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/weblogic.xml
=> change prefer-web-inf-classes from false to true. #383

terasoluna-gfw-functionaltest-env/configs/interstage11-oracle/ContainerConfig/deleteInterstageResources.sh, terasoluna-gfw-functionaltest-env/configs/interstage11-oracle/ContainerConfig/deleteInterstageResources.sh.env.ftl, terasoluna-gfw-functionaltest-env/configs/interstage11-oracle/ContainerConfig/setInterstageResources.sh, terasoluna-gfw-functionaltest-env/configs/interstage11-oracle/ContainerConfig/setInterstageResources.sh.env.ftl
@ikeyat , please review #339 .
=> add scripts for jenkins. #339

CONTRIBUTING.md, README.md
=> #266: Create README.md & CONTRIBUTING.md

CONTRIBUTING.md, README.md
I've backported to 5.0.x.
Please review #266 .
=> [5.0.x] Create README.md & CONTRIBUTING.md #266

CONTRIBUTING.md, README.md
I've backported to 1.0.x.
Please review #266.
=> [1.0.x] Create README.md & CONTRIBUTING.md #266

.travis.yml
=> fix travix.yml #400

terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-parent/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> Update to 1.0.5-SNAPSHOT #392

terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-parent/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> Update to 5.0.3-SNAPSHOT #393

terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-parent/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> Update to 5.1.1-SNAPSHOT #394

terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-parent/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> Update to 5.2.0-SNAPSHOT #395

ISSUE_TEMPLATE.md, PULL_REQUEST_TEMPLATE.md
=> Add issue and PR template #404

terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/service/sequencer/SequencerService.java, terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/service/sequencer/SequencerServiceImpl.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/sequencer/SequencerTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/sequencer/SequencerController.java, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/sequencer/index.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/sequencer/showCurrval.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/sequencer/showSameTransaction.jsp
=> Add same-transaction test-case in sequencer.#407

.travis.yml, pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
Please review #302.
Cherry-picked from #424.
=> [5.1.x] apply multi module project #302

.travis.yml, pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
Please review #302.
Cherry-picked from #424.
=> [5.0.x] apply multi module project #302 

.travis.yml, pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
Please review #302.
Cherry-picked from #424.
=> [1.0.x] apply multi module project #302 

README.md
=> update readme.md for apply multi module projects #302

README.md
Please review #302.
( Cherry-picked from #437 )
=> [5.1.x] update readme.md for apply multi module projects #302 

README.md
Please review #302
( Cherry-picked from #437,#438 )
=> [5.0.x] update readme.md for apply multi module projects #302 

README.md
Please review #302
( Cherry-picked from #437,#438 )
=> [1.0.x] update readme.md for apply multi module projects #302 

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/FirefoxDriverFactoryBean.java, terasoluna-gfw-functionaltest-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
=> add FirefoxDriverFactoryBean #432

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/FirefoxDriverFactoryBean.java, terasoluna-gfw-functionaltest-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
=> [5.1.x] add FirefoxDriverFactoryBean #432

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/FirefoxDriverFactoryBean.java, terasoluna-gfw-functionaltest-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
=> [5.0.x] add FirefoxDriverFactoryBean #432

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/FirefoxDriverFactoryBean.java, terasoluna-gfw-functionaltest-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
=> [1.0.x] add FirefoxDriverFactoryBean #432

terasoluna-gfw-functionaltest-web/src/main/resources/hibernate.properties
=> add hibernate.properties #441

terasoluna-gfw-functionaltest-web/src/main/resources/hibernate.properties
Please review #441 .
(cherry picked from commit a65fbdd3ef7988c0c3b2858a495e798e1e0ef032)
=> [5.1.x] add hibernate.properties #441

.travis.yml, README.md, pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml
=> change jdbc driver scopes #451

README.md
Sorry, I made a mistake in #454. Please merge this #451.
=> change jdbc drivers (readme) #451

.travis.yml, README.md, pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml
Please review #451.
(Backport from #454, #455)
=> [5.1.x] change jdbc driver scopes #451

.travis.yml, README.md, pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml
Please review #451.
(Backport from #454, #455)
=> [5.0.x] change jdbc driver scopes #451

.travis.yml, README.md, pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml
Please review #451.
(Backport from #454, #455)
=> [1.0.x] change jdbc driver scopes #451

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/date/DateTest.java
=> fixed day crossing time test failure (DateTest.test03_05_adjustedDateReturn) #274 

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/date/DateTest.java
Please review #274 .
(backport to 5.1.x)
=> fix day crossing time test backport 5.1.x

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/date/DateTest.java
Please review #274 .
(backport to 5.0.x)
=> fix day crossing time test backport 5.0.x

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/date/DateTest.java
Please review #274 .
(backport to 1.0.x)
=> fix day crossing time test backport 1.0.x

eclipse/formatter.xml, pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> apply new pom structure #428

eclipse/formatter.xml
=> [5.1.x] Add Formatter File. #448

pom.xml
=> add new comments to categorize properties #428

eclipse/formatter.xml
Please review #448 .
(backport to 5.0.x)
=> 5.0.x_backport_Add Formatter File. #448

eclipse/formatter.xml
Please review #448 .
(backport to 1.0.x)
=> 1.0.x_backport_Add Formatter File. #448

terasoluna-gfw-functionaltest-web/pom.xml
=> modify dependency #428

terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-common.xml
Please review #471 .
The regression tests succeeded.
=> add workaround settings for CVE-2016-5007 to master  #471

terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-common.xml
Please review #471 .
The regression tests succeeded.
=> add workaround settings for CVE-2016-5007 to 5.1.x #471

terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-common.xml
Please review #471.
The regression tests succeeded.
=> add workaround settings for CVE-2016-5007 to 5.0.x #471

terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-common.xml
Please review #471.
The regression tests succeeded.
=> add workaround settings for CVE-2016-5007 to 1.0.x #471

pom.xml
Sorry, this is bug fix of #302.
=> correct project.env.main.directory #302

pom.xml
Sorry, this is bug fix of #302.
=> [5.1.x] correct project.env.main.directory #302

pom.xml
Sorry, this is bug fix of #302.
Actual change is line 227 only.
(cherry picked from commit 251ca37273fbd495244f137bf1146c2ace11e38d)
Conflicts:
pom.xml
=> [5.0.x] correct project.env.main.directory #302

pom.xml
Sorry, this is bug fix of #302.
(cherry picked from commit 251ca37273fbd495244f137bf1146c2ace11e38d)
Conflicts:
pom.xml
=> [1.0.x] correct project.env.main.directory #302

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/transactiontoken/TransactionTokenTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/transactiontoken/TransactionTokenFlow1Controller.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/transactiontoken/TransactionTokenFlow2Controller.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/transactiontoken/TransactionTokenFlow7Controller.java, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/flow1NamespaceStep3.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/flow1Step2.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/flow1Step3.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/flow2Step3.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/flowAllNamespaceStep1.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/flowAllStep1.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/index.jsp
Please review #463 .
@ikeyat 
---
https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/pull/473/commits/8d9d46d3daf4bb150423584ad20172f8705ab564
add test cases with the additon of the test item. by @btsaitoumsw
=> add testCase of TransactionToken. #463

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/transactiontoken/TransactionTokenTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/transactiontoken/TransactionTokenFlow1Controller.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/transactiontoken/TransactionTokenFlow2Controller.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/transactiontoken/TransactionTokenFlow7Controller.java, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/flow1NamespaceStep3.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/flow1Step2.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/flow1Step3.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/flow2Step3.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/flowAllNamespaceStep1.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/flowAllStep1.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/index.jsp
Please review #463 .
Cherry-picked from #473 .
=> [5.1.x] add testCase of TransactionToken. #463

README.md
=> modify the description as make it use mvn command. #483

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/transactiontoken/TransactionTokenTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/transactiontoken/TransactionTokenFlow1Controller.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/transactiontoken/TransactionTokenFlow2Controller.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/transactiontoken/TransactionTokenFlow7Controller.java, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/flow1NamespaceStep3.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/flow1Step2.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/flow1Step3.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/flow2Step3.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/flowAllNamespaceStep1.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/flowAllStep1.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/index.jsp
Please review #463 .
[Removed some words by @ikeyat]
=> TransactionType reduction. #463

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/transactiontoken/TransactionTokenTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/transactiontoken/TransactionTokenFlow1Controller.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/transactiontoken/TransactionTokenFlow2Controller.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/transactiontoken/TransactionTokenFlow7Controller.java, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/flow1NamespaceStep3.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/flow1Step2.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/flow1Step3.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/flow2Step3.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/flowAllNamespaceStep1.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/flowAllStep1.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/transactiontoken/index.jsp
Please review #463.
(cherry picked from commit b3ef37f901f03baa41eadc382a1b3643180dbaae)
=> [5.1.x] TransactionType reduction. #463

pom.xml
=> resolve warning of maven-install-plugin version #487

.travis.yml
Modify  GFW_BRANCH 
master　 →　5.2.x
Please review .
=> Modify travis.yml#846

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> Update version to 5.3.0-SNAPSHOT in master.#489

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> Update version to 5.2.1-SNAPSHOT in 5.2.x.#489

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> Update version to 5.1.2-SNAPSHOT in 5.1.x.#489

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> Update version to 1.0.6-SNAPSHOT in 1.0.x.#489

README.md
=> fix travis-ci badge in README.md on 5.2.x #497

README.md
=> fix travis-ci badge in README.md on 5.1.x #497

terasoluna-gfw-functionaltest-initdb/pom.xml
Please review #500.
(cherry picked from commit f9afeb6ccf0d1a39ae22eeefe8cd45dfebc75a9c)
=> [5.2.x] change db2 user account #500

terasoluna-gfw-functionaltest-initdb/pom.xml
=> change db2 user account #500

terasoluna-gfw-functionaltest-initdb/pom.xml
Please review #500.
(cherry picked from commit f9afeb6ccf0d1a39ae22eeefe8cd45dfebc75a9c)
=> [5.1.x] change db2 user account #500

pom.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-infra.properties, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/resources/META-INF/web-fragment.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/resources/log4jdbc.properties, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/resources/logback-ddl.sql, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/resources/logback.xml
=> create profile for tomcat85-postgreSQL9 #506

pom.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-infra.properties, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/resources/META-INF/web-fragment.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/resources/log4jdbc.properties, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/resources/logback-ddl.sql, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/resources/logback.xml
=> create profile for tomcat85-oracle #508

pom.xml
=> fixed the indent in pom file #506

README.md
=> add hints in README.md about firefox version

README.md
Please review #504 .
This is a backport request for 5.2.x.
Original pull request was #505
=> add firefox version hint #504, backport for 5.2.x

README.md
Please review #504 .
This is a backport request for 5.1.x.
original pull request #505
=> add firefox version hint #504, backport for 5.1.x

README.md
Please review #504 .
This is a backport request.
=> add firefox version hint #504, backport for 5.0.x

pom.xml
=> update db2jcc4.jar version #521

pom.xml
Please review #521.
(cherry picked from commit 2dec558f4d51cbd13082eb9f3b7d15283b5c8c55)
=> [5.2.x] update db2jcc4.jar version #521

pom.xml
Please review #521.
(cherry picked from commit 2dec558f4d51cbd13082eb9f3b7d15283b5c8c55)
=> [5.1.x] update db2jcc4.jar version #521

pom.xml, terasoluna-gfw-functionaltest-env/configs/jboss7-postgresql/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/jboss7-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/jboss7-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-infra.properties, terasoluna-gfw-functionaltest-env/configs/jboss7-postgresql/resources/META-INF/web-fragment.xml, terasoluna-gfw-functionaltest-env/configs/jboss7-postgresql/resources/log4jdbc.properties, terasoluna-gfw-functionaltest-env/configs/jboss7-postgresql/resources/logback-ddl.sql, terasoluna-gfw-functionaltest-env/configs/jboss7-postgresql/resources/logback.xml, terasoluna-gfw-functionaltest-env/configs/jboss7-postgresql/webapp/WEB-INF/jboss-deployment-structure.xml
I have created profile for jboss7-postgresql based on jboss6-postgresql's.
Please review #507 .
=> create profile for jboss7-postgresql

pom.xml, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/WebDriverEventListenerAdapter.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/el/ElTest.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/redirect/RedirectController.java, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-common.xml
Please review #517 ( #513 #514 #515 #516 #526 ).
=> expectation correction of the assertion error #517

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingController.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ThrowIOExceptionFilter.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ThrowIndexOutOfBoundsExceptionFilter.java, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/exceptionhandling/index.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/web.xml
Please review #517 .
I updated the test in order to apply the change of the test case design.
=> test case 4.2 was deleted and added to 3.11 #517

pom.xml
=> update java-version 1.7 -> 1.8 #528

.travis.yml
=> Change to export CARGO_DAEMON_WEBAPP_VERSION dynamically #538

terasoluna-gfw-functionaltest-env/configs/jboss-postgresql/webapp/WEB-INF/jboss-deployment-structure.xml
=> exclude jboss logging module #545

pom.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-infra.properties, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/resources/META-INF/web-fragment.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/resources/log4jdbc.properties, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/resources/logback-ddl.sql, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/resources/logback.xml
cherry picked from commit a0485a2cb399bd0f742d4176a6d40a7f19140c96 and  99b62d70c7b14187a0cd7da35f1652a4dc9c8522.
Please review #506 .
=> create tomcat85-postgresql9 profile on 5.2.1 #506

pom.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-infra.properties, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/resources/META-INF/web-fragment.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/resources/log4jdbc.properties, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/resources/logback-ddl.sql, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/resources/logback.xml
(cherry picked from commit 30a2e9595de3e9c94b2ae49a817ca467a29ea3b5)
Please review #508.
=> create tomcat85-oracle12 profile on 5.2.1

pom.xml
=> update Postgresql JDBC Driver version. #549

terasoluna-gfw-functionaltest-env/configs/interstage11-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/webotx-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/webspherelp-db2/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/webspheretr-db2/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
=> [5.3.x]add settings that DataSourceTransactionManager#setRollbackOnCommitFaillure=true in xml files what using DataSourceTransactionManager.

terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/travis/ContainerConfigXML/context.xml
=> Set defaultAutoCommit to false in context.xml #561

terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/travis/ContainerConfigXML/context.xml
(cherry picked from commit 5a4a562fd507fe39fff03ab4c1fdf2cfc8436a1a)
Please review #561.
=> [5.2.x] Set defaultAutoCommit to false in context.xml #561

terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/travis/ContainerConfigXML/context.xml
=> [5.1.x] Set defaultAutoCommit to false in context.xml #561

terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/travis/ContainerConfigXML/context.xml
(cherry picked from commit 106fe6b7af2d8bbd61819bb38d942940fcbea4ba)
Please review #561.
=> [5.0.x] Set defaultAutoCommit to false in context.xml #561

terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/travis/ContainerConfigXML/context.xml
=> [1.0.x] Set defaultAutoCommit to false in context.xml #561

terasoluna-gfw-functionaltest-env/configs/interstage11-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/webotx-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/webspherelp-db2/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
Please review #555 .
PR #556 の5.2.x版バックポートです。
=> [5.2.x]add settings that DataSourceTransactionManager#setRollbackOnCommitFaillure=true in xml files what using DataSourceTransactionManager.  

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/FirefoxDriverFactoryBean.java
=> modify properties #567

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/FirefoxDriverFactoryBean.java
(cherry picked from commit 9554445e9e5b423f6bf86d044031d94258e48af4)
Please review #567.
=> [5.2.x]modify properties #567

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/FirefoxDriverFactoryBean.java
(cherry picked from commit 9554445e9e5b423f6bf86d044031d94258e48af4)
Please review #567.
=> [5.1.x]modify properties #567

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/FirefoxDriverFactoryBean.java
(cherry picked from commit 9554445e9e5b423f6bf86d044031d94258e48af4)
Please review #567.
=> [5.0.x]modify properties #567

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/FirefoxDriverFactoryBean.java
(cherry picked from commit 9554445e9e5b423f6bf86d044031d94258e48af4)
Please review #567.
=> [1.0.x]modify properties #567

README.md
add attention for README.md when using JDK7 .
=> update README.md for jdk7 #528

README.md
This branch is backport branch for 5.2.x from #575
=> [5.2.x] update README.md for jdk7 #528

README.md
This branch is backport branch for 1.0.x from #575
=> [1.0.x] update README.md for jdk7 #528

README.md
This branch is backport branch for 5.1.x from #575
=> [5.1.x] update README.md for jdk7 #528

README.md
This branch is backport branch for 5.0.x from #575
=> [5.0.x] update README.md for jdk7 #528

terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc.xml
=> Adjust excludedExceptions to guidelines. #517

pom.xml
=> Modified /pom.xml for Maven Central.#560

terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/travis/ContainerConfigXML/context.xml
Reverts terasolunaorg/terasoluna-gfw-functionaltest#562
See  #561
=> Revert "Set defaultAutoCommit to false in context.xml #561"

terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/travis/ContainerConfigXML/context.xml
Reverts terasolunaorg/terasoluna-gfw-functionaltest#563
See  #561
=> Revert "[5.2.x] Set defaultAutoCommit to false in context.xml #561"

terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/travis/ContainerConfigXML/context.xml
Reverts terasolunaorg/terasoluna-gfw-functionaltest#564
See  #561
=> Revert "[5.1.x] Set defaultAutoCommit to false in context.xml #561"

terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/travis/ContainerConfigXML/context.xml
Reverts terasolunaorg/terasoluna-gfw-functionaltest#565
See  #561
=> Revert "[5.0.x] Set defaultAutoCommit to false in context.xml #561"

terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/travis/ContainerConfigXML/context.xml
Reverts terasolunaorg/terasoluna-gfw-functionaltest#566
See  #561
=> Revert "[1.0.x] Set defaultAutoCommit to false in context.xml #561"

pom.xml
=> Remove org.codehaus.cargo.cargo-maven2-plugin.version property in pom.xml #537

README.md
=> [master]Update README.md (2017 winter) #610

README.md
=> [5.3.x]Update README.md (2017 winter) #610

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> [master]Update version to 5.4.0-SNAPSHOT.#611

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> [5.3.x]Update version to 5.3.1-SNAPSHOT.#611

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> [5.2.x]Update version to 5.2.2-SNAPSHOT.#611

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> [1.0.x]Update version to 1.0.7-SNAPSHOT.#611

.travis.yml
=> Change to use terasoluna-gfw 5.3.x branch at .travis of 5.3.x branch #619

README.md
=> [1.0.x]Update README.md (2017 winter) #610

README.md
=> [5.0.x]Update README.md (2017 winter) #610

README.md
=> [5.1.x]Update README.md (2017 winter) #610

README.md
=> [5.2.x]Update README.md (2017 winter) #610

terasoluna-gfw-functionaltest-env/configs/interstage11-oracle/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/jboss-postgresql/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/jboss7-postgresql/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/weblogic-oracle/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/webotx-oracle/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/webspherelp-db2/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/webspheretr-db2/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/src/main/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/ApServerName.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/WebDriverOperations.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/logging/LoggingTest.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/redirect/RedirectTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/PropertySourceConfig.java, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/applicationContext.xml, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/layout/template.jsp
This PR is backport for 5.3.x .
=> [5.3.x]recognize ap server, and remove @ignore at ExceptionHandlingTest #605

terasoluna-gfw-functionaltest-env/configs/interstage11-oracle/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/jboss-postgresql/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/weblogic-oracle/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/webotx-oracle/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/webspherelp-db2/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/src/main/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/ApServerName.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/WebDriverOperations.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/logging/LoggingTest.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/redirect/RedirectTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/PropertySourceConfig.java, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/applicationContext.xml, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/layout/template.jsp
This PR is backport for 5.2.x .
=> [5.2.x]recognize ap server #605

terasoluna-gfw-functionaltest-env/configs/interstage11-oracle/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/jboss-postgresql/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/weblogic-oracle/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/webotx-oracle/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/webspherelp-db2/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/src/main/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/ApServerName.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/WebDriverOperations.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/logging/LoggingTest.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/redirect/RedirectTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/PropertySourceConfig.java, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/applicationContext.xml, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/layout/template.jsp
This PR is backport for 5.1.x .
=> [5.1.x]recognize ap server #605

terasoluna-gfw-functionaltest-env/configs/jboss-postgresql/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/weblogic-oracle/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/src/main/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/ApServerName.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/WebDriverOperations.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/logging/LoggingTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/PropertySourceConfig.java, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/applicationContext.xml, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/layout/template.jsp
This PR is backport for 5.0.x .
=> [5.0.x]recognize ap server #605

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/validation/ValidationTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/validation/ValidationController.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/validation/ValidationForm.java, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/validation/compare.jsp
=> Add test for NOT_EQUAL using @Compare #647

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingController.java, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-change-attribute.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-change-default-status-code.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-exceptionlogger-variation.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-ignore-result-messages.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-log-format.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-message-exception-coderesolver.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-redirect.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc.xml, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/exceptionhandling/index.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/web.xml
=> Modified incorrect test codes. #643

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java
=> Resolve TODO in TestCase. #627

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionCodeExceptionLoggingFilter.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/VariationExceptionLoggingFilter.java, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/applicationContext.xml, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/web.xml
=> Modify test cases for logging of Exception Handling. #642

.travis.yml
=> add firefox version at .travis.yml #655

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingController.java, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-change-attribute.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-change-default-status-code.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-exceptionlogger-variation.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-ignore-result-messages.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-log-format.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-message-exception-coderesolver.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-redirect.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc.xml, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/exceptionhandling/index.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/web.xml
Please review #643.
This pull request is backport for 5.3.1
=> [5.3.x] modify incorrect test cases for logging of exception handling #643

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingController.java, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-change-attribute.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-change-default-status-code.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-exceptionlogger-variation.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-ignore-result-messages.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-log-format.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-message-exception-coderesolver.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-redirect.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc.xml, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/exceptionhandling/index.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/web.xml
Please review #643 .
This pull request is backport for 5.2.2
=> [5.2.x] modify incorrect test cases for logging of exception handling #643

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingController.java, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-change-attribute.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-change-default-status-code.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-exceptionlogger-variation.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-ignore-result-messages.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-log-format.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-message-exception-coderesolver.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-redirect.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc.xml, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/exceptionhandling/index.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/web.xml
Please review #643.
This pull request is backport for 5.1.2
=> [5.1.x] modify incorrect test cases for logging of exception handling #643

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingController.java, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-change-attribute.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-change-default-status-code.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-exceptionlogger-variation.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-ignore-result-messages.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-log-format.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-message-exception-coderesolver.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-redirect.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc.xml, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/exceptionhandling/index.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/web.xml
Please review #643.
This pull request is backport for 5.0.3.
=> [5.0.x] modify incorrect test cases for logging of exception handling #643

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingController.java, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-change-attribute.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-change-default-status-code.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-exceptionlogger-variation.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-ignore-result-messages.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-log-format.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-message-exception-coderesolver.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-redirect.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc.xml, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/exceptionhandling/index.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/web.xml
Please review #643 .
This pull request is backport for 1.0.7
=> [1.0.x] modify incorrect test cases for logging of exception handling #643

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java
This pull request is backport for 5.3.1.
=> [5.3.x] Resolve todo in test case. #627

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java
This pull request is backport for 5.2.2.
=> [5.2.x] Resolve todo in test case. #627

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java
This pull request is backport for 5.1.2.
=> [5.1.x] Resolve TODO in test case. #627

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java
This pull request is backport for 5.0.3.
=> [5.0.x] Resolve TODO in test case. #627

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java
This pull request is backport for 1.0.7.
=> [1.0.x] Resolve TODO in test case. #627

ISSUE_TEMPLATE.md
=> Add Final Solution section to Issue Template. #673

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java
=> extend wait for assertion time.#675

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java
=> [5.3.x] extend wait for assertion time.#675

terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-common.xml
=> Remove definition of trimTokens #682

terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-common.xml
=> [5.3.x]Remove definition of trimTokens #682

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java
=> [5.2.x] extend wait for assertion time.#675

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java
(cherry picked from commit c37451cc541807dbf1fd9862800e5a7be9bef186)
Please review #675
=> [5.1.x] extend wait for assertion time.#675

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java
(cherry picked from commit c37451cc541807dbf1fd9862800e5a7be9bef186)
Please review #675.
=> [5.0.x] extend wait for assertion time.#675

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java
=> [1.0.x] extend wait for assertion time.#675

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> [5.3.x] fix SNAPSHOT version in pom.xml #704

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> update to 5.5.0-SNAPSHOT #709

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> [5.4.x] update to 5.4.1-SNAPSHOT #709

README.md
=> [5.4.x] change link to badge in README.md #708

.travis.yml
=> travis ci broken using selenium #706

.travis.yml
=> change GFW_BRANCH to 5.4.x #715

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> [5.4.x] update snapshot version to 5.4.2 #723

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> [5.3.x] update snapshot version to 5.3.3 #723

.travis.yml, pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> update to 5.5.0.RC2-SNAPSHOT #729

.travis.yml, pom.xml, terasoluna-gfw-functionaltest-env/configs/tomcat9-postgresql/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat9-postgresql/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat9-postgresql/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/tomcat9-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat9-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-infra.properties, terasoluna-gfw-functionaltest-env/configs/tomcat9-postgresql/resources/META-INF/web-fragment.xml, terasoluna-gfw-functionaltest-env/configs/tomcat9-postgresql/resources/log4jdbc.properties, terasoluna-gfw-functionaltest-env/configs/tomcat9-postgresql/resources/logback-ddl.sql, terasoluna-gfw-functionaltest-env/configs/tomcat9-postgresql/resources/logback.xml
=> add profile for tomcat9-postgresql #726

terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/applicationContext.xml
=> fix dozer beanMapper definition. #733

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/el/ElTest.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/pagination/PaginationTest.java
=> remove the plus symbol from selenium #735

terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/service/codelist/CodeListServiceImpl.java, terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/service/redirect/RedirectServiceImpl.java
=> fix to findById because findOne is gone #731

pom.xml
=> update postgresql driver version #737

.travis.yml, README.md, pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/FirefoxDriverFactoryBean.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/FunctionTestSupport.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/WaitWebDriverEventListener.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/WebDriverEventListenerAdapter.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/WebDriverOperations.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/codelist/CodeListTest.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/el/ElTest.java, terasoluna-gfw-functionaltest-selenium/src/test/resources/META-INF/spring/selenium.properties, terasoluna-gfw-functionaltest-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
=> Update from Selenium 2 to Selenium 3 #740

terasoluna-gfw-functionaltest-selenium/src/test/resources/META-INF/spring/selenium.properties
=> Fix selenium3 error occurring in travis. #748

pom.xml, terasoluna-gfw-functionaltest-env/configs/tomcat9-oracle/ContainerConfigXML/context.xml, terasoluna-gfw-functionaltest-env/configs/tomcat9-oracle/ContainerConfigXML/context.xml.env.ftl, terasoluna-gfw-functionaltest-env/configs/tomcat9-oracle/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/tomcat9-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat9-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-infra.properties, terasoluna-gfw-functionaltest-env/configs/tomcat9-oracle/resources/META-INF/web-fragment.xml, terasoluna-gfw-functionaltest-env/configs/tomcat9-oracle/resources/log4jdbc.properties, terasoluna-gfw-functionaltest-env/configs/tomcat9-oracle/resources/logback-ddl.sql, terasoluna-gfw-functionaltest-env/configs/tomcat9-oracle/resources/logback.xml
=> add profile for tomcat9-oracle #746

pom.xml
=> update ver postgresql #752

ISSUE_TEMPLATE.md
Please review #755.
- Delete `Final Solution` 
- Add version template into `Fix Version/s`
- Change markdown syntax for listing
=> update issue template #755

.travis.yml, pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java, terasoluna-gfw-functionaltest-web/pom.xml
=> apply spring boot dependencies 2.1.2 #761 #762 #763

.travis.yml
=> fix build profile of terasoluna-gfw #762

terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-common.xml
=> Modify the way to set thredhold time of TraceLoggingInterceptor #764

README.md
=> update readme about java version #762

terasoluna-gfw-functionaltest-selenium/src/test/resources/META-INF/spring/selenium.properties
=> delete property of selenium #771

terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-common.xml
(cherry picked from commit b0edf89e422aa532fac4a41733da4817c833f775)
Please review #764.
=> [5.4.x] Modify the way to set thredhold time of TraceLoggingInterceptor #764

terasoluna-gfw-functionaltest-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
=> correct typo #626

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/validation/ValidationTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/validation/ValidationController.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/validation/ValidationForm.java, terasoluna-gfw-functionaltest-web/src/main/resources/ValidationMessages.properties, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/validation/bytesize.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/validation/index.jsp
Please review #776 .
Please re-build with Travis CI after merging terasolunaorg/terasoluna-gfw#762 .
=> apply @ByteSize #776

terasoluna-gfw-functionaltest-domain/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-codelist.xml, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/codelist/CodeListTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codelist/CodeListController.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codelist/ExistInCheckForm.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codelist/ExistInCheckWrongCodeListForm.java, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/08_03_form.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/08_04_form.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/08_05_form.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/08_07_form.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/08_08_form.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/08_09_form.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/08_10_form.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/index.jsp
=> @ExistInCodeList enable to validate Number #779

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml
=> update jdbc driver #781

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/codelist/CodeListTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codelist/CodeListController.java, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/10_02_form.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/index.jsp
=> make reloadable codelist immutable #784

terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/model/I18nItemCode.java, terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/repository/codelist/I18nCodeListRepository.java, terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/service/codelist/I18nCodeListService.java, terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/service/codelist/I18nCodeListServiceImpl.java, terasoluna-gfw-functionaltest-domain/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-codelist.xml, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/codelist/CodeListTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codelist/CodeListController.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codelist/I18nCodeListForm.java, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/12_01_form.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/index.jsp
=> new feature reloadable i18n codelist #785

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/PageSource.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/queryescape/QueryEscapeTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/el/ElMapOfSimpleValueDefaultTrimController.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/message/MessageController.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/pagination/PaginationController.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/transactiontoken/TransactionTokenFlow1Controller.java
Please review #788.
`@SuppressWarnings("deprecation")` test for terasoluna-gfw deprecated APIs.
=> resolve deprecated api #788

terasoluna-gfw-functionaltest-env/configs/weblogic-oracle/webapp/WEB-INF/weblogic.xml
=> Change to use prefer-application-packages #790

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/validation/ValidationTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/validation/ValidationController.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/validation/ValidationForm.java, terasoluna-gfw-functionaltest-web/src/main/resources/ValidationMessages.properties, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/validation/bytesize.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/validation/index.jsp
(cherry picked from commit aa0b6b7b5847357d089528a0936e2293dff72770)
Please review #776.
**Please re-build after merge terasolunaorg/terasoluna-gfw#885.**
=> [5.4.x] apply @ByteSize #776

terasoluna-gfw-functionaltest-domain/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-codelist.xml, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/codelist/CodeListTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codelist/CodeListController.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codelist/ExistInCheckForm.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codelist/ExistInCheckWrongCodeListForm.java, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/08_03_form.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/08_04_form.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/08_05_form.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/08_07_form.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/08_08_form.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/08_09_form.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/08_10_form.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/index.jsp
Please review #779 .
**Please re-build after merge terasolunaorg/terasoluna-gfw#887.**
=> [5.4.x] @ExistInCodeList enable to validate Number #779

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/codelist/CodeListTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codelist/CodeListController.java, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/10_02_form.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/index.jsp
(cherry picked from commit a999913ca0993a457176e04886b721db060c7848)
Please review #784.
**Please re-build after merge terasolunaorg/terasoluna-gfw#888.**
=> [5.4.x] make reloadable codelist immutable #784

.travis.yml, pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> udpate to 5.5.2-SNAPSHOT #795

ISSUE_TEMPLATE.md, pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> update to 5.6.0-SNAPSHOT #795

terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/model/I18nItemCode.java, terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/repository/codelist/I18nCodeListRepository.java, terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/service/codelist/I18nCodeListService.java, terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/service/codelist/I18nCodeListServiceImpl.java, terasoluna-gfw-functionaltest-domain/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-codelist.xml, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/codelist/CodeListTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codelist/CodeListController.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codelist/I18nCodeListForm.java, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/12_01_form.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/index.jsp
(cherry picked from commit 2f51fdec9f98fd6f580356d7d01fda0324befa83)
Please review #785 .
**Please re-build and merge after terasolunaorg/terasoluna-gfw#894.**
5.4 does not have tests 11.x for CodeList,
because there is no changes of "improve i18n codelist locale resolution".
=> [5.4.x] new feature reloadable i18n codelist #785

terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/exception/InfoLogging.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codelist/ExistInSampleCodeList.java
=> Make the validator compliant with Bean Validation 2.0 #800

terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/exception/InfoLogging.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codelist/ExistInSampleCodeList.java
Please review #800 .
This PR is backport for 5.5.x .
=> [5.5.x] Make the validator compliant with Bean Validation 2.0 #800

terasoluna-gfw-functionaltest-domain/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-codelist.xml, terasoluna-gfw-functionaltest-domain/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-domain.xml, terasoluna-gfw-functionaltest-domain/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-infra.xml, terasoluna-gfw-functionaltest-domain/src/test/resources/META-INF/spring/terasoluna-gfw-functionaltest-infra-mybatis.xml, terasoluna-gfw-functionaltest-domain/src/test/resources/test-context.xml, terasoluna-gfw-functionaltest-env/configs/interstage11-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/jboss-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/jboss7-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/weblogic-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/webotx-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/configs/webspherelp-db2/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-env/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml, terasoluna-gfw-functionaltest-selenium/src/test/resources/META-INF/spring/seleniumContext.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/applicationContext.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-common.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-change-attribute.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-change-default-status-code.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-exceptionlogger-variation.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-ignore-result-messages.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-log-format.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-message-exception-coderesolver.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-redirect.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-security.xml
=> [5.4.x] replace schema location for spring from http to https #807

terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/exception/InfoLogging.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codelist/ExistInSampleCodeList.java
=> [5.4.x] Make the validator compliant with Bean Validation 1.1 #800

.travis.yml
Please review #814 #813 #819 .
=> Change Oracle JDK -> Open JDK #814 Adapt xvfb usage at Xenial environment #813 Suppress log output #819

.travis.yml, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/codelist/CodeListTest.java
=> [Spring Framework 5.1.7] Avoid MessageFormat processing for default Bean Validation messages #821 Apply development/5.6.0 #822

terasoluna-gfw-functionaltest-domain/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-codelist.xml
Please review #807.
This PR corresponds to the work omission of https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/pull/825 .
=> modify URL without version #807

.travis.yml
Please review #814 #813 #819 .
Cherry-pick from commit 6e05e13892eb1e6f4e0294be6fc93d9f7ede5d84 , c7464afd591225633e80b051dabfbf2d4368e0f8, 8e40080b477bb872cdf1c674a88c5f60926d0d84 .
=> [5.5.x] Change Oracle JDK -> Open JDK #814 Adapt xvfb usage at Xenial environment #813 Suppress log output #819

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/pagination/PaginationTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/pagination/PaginationController.java, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/pagination/index.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/pagination/innerElementClass.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/resources/app/css/style.css
Please review #826 .
**Please re-run Travis CI after mergeing terasolunaorg/terasoluna-gfw#932**
=> add innerElementClass attribute to pagination tag. #826

terasoluna-gfw-functionaltest-web/src/main/resources/ValidationMessages.properties
=> remove validation messages for common libraries #817

terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/applicationContext.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-security.xml
=> fix passwordEncoder to DelegatingPasswordEncoder #840

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml
=> update JDBC driver #836

terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/repository/customer/CustomerSearchCriteria.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/el/ElTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/el/SearchUserCriteriaForm1.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/el/SearchUserForm1.java, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/el/beanQueryOutput.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/el/nestedJavaBeanQueryOutput.jsp
=> fix test target property #844

terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> upgrade hamcrest to 2.x #846

pom.xml
=> upgrade jdbc 42.2.9 #836

terasoluna-gfw-functionaltest-env/configs/interstage11-oracle/resources/logback.xml, terasoluna-gfw-functionaltest-env/configs/jboss-postgresql/resources/logback.xml, terasoluna-gfw-functionaltest-env/configs/jboss7-postgresql/resources/logback.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/resources/logback.xml, terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/resources/logback.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/resources/logback.xml, terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/resources/logback.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/resources/logback.xml, terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/resources/logback.xml, terasoluna-gfw-functionaltest-env/configs/tomcat9-oracle/resources/logback.xml, terasoluna-gfw-functionaltest-env/configs/tomcat9-postgresql/resources/logback.xml, terasoluna-gfw-functionaltest-env/configs/weblogic-oracle/resources/logback.xml, terasoluna-gfw-functionaltest-env/configs/webotx-oracle/resources/logback.xml, terasoluna-gfw-functionaltest-env/configs/webspherelp-db2/resources/logback.xml, terasoluna-gfw-functionaltest-env/src/main/resources/logback.xml
=> change loglevel of Repository to trace to log ResultSet #837

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> update 5.7.0-SNAPSHOT #865

README.md, pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> update 5.6.1-SNAPSHOT #865

terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/exception/InfoLogging.java, terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/service/queryescape/DatabaseMetaInfoServiceMybatis3Impl.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/FunctionTestSupport.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/codelist/CodeListTest.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/codepoints/CodePointsTest.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/codepoints/ConsistOfCheckTest.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/date/DateTest.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/download/DownloadTest.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/el/ElTest.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/logging/LoggingTest.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/message/MessageTest.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/pagination/PaginationTest.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/queryescape/QueryEscapeTest.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/redirect/RedirectTest.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/sequencer/SequencerTest.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/string/FullHalfConverterTest.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/transactiontoken/TransactionTokenTest.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/validation/ValidationTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/codelist/ExistInSampleCodeList.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/date/DateController.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/redirect/RedirectController.java, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-common.xml, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/redirect/externalPathWithContextPath.jsp
Please review #870 #871 #872 #873 #874.
**Please do not squash. All commits must be independent.**
=> apply spring boot 2.4.0-M2 #870 #871 #872 #873 #874

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/codelist/CodeListTest.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/codepoints/ConsistOfCheckTest.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/validation/ValidationTest.java, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codelist/index.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/codepoints/index.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/validation/index.jsp
=> apply to provide ContributorValidationMessages_ja.properties #877

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml
=> Change the groupId of the OracleJDBCDriver #879

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml
(cherry picked from commit 8de73fe9a774540230f2aef7ea86f527a00dfb14)
Please review #881.
Original PR #880
=> [5.6.x]Change the groupId of the OracleJDBCDriver #881

terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-common.xml
=> Remove unused execlude-mapping settings #876

terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-common.xml
Please review #883.
Operation check procedure:
- Tested on travis ci.
=> [5.6.x]Remove unused execlude-mapping settings #883

.travis.yml
Please review #865.
Confirmation method:
- When I checked the parameters of travis.ci below, I confirmed that the correction was reflected.
https://travis-ci.org/github/terasolunaorg/terasoluna-gfw-functionaltest/builds/731529271/config
=> Change GFW_BRANCH to 5.6.x #865

terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/service/date/DateServiceImpl.java
Please review #864 .
Confirmation:
- Operation check：Confirming that all results for travis ci will be successful.
- Identify what needs to be fixed：Change \<java-version> of pom to 11 and check if there are any deprecated warnings on STS.
=> Fixed deprecated API in jdk9 #864

terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/service/date/DateServiceImpl.java
=> [5.6.x]Fixed deprecated API in jdk9 #864 

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/message/MessageTest.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/pagination/PaginationTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/message/MessageController.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/pagination/PaginationController.java, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/message/index.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/pagination/anchorClass.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/pagination/index.jsp
=> make the tag library compatible with Bootstrap v4 #896

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/DBLog.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/PageSource.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/ScreenCapture.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/VariationExceptionLevelResolver.java
=> resolve spring 5.3.0 deprecated StringUtils#isEmpty #899

.travis.yml
(cherry picked from commit 9c849911f177e44f063998fb4ebcc5fd99a47bdd)
please review https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/894#issuecomment-745716377 .
This is a correction omission that was handled by https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/pull/895#discussion_r537210379 .
=> setting param PGPORT. #894

terasoluna-gfw-functionaltest-env/configs/jboss7-postgresql/webapp/WEB-INF/jboss-deployment-structure.xml
Please review https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/904#issuecomment-759125585 .
=> exclude sub-system jsf. #904

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> update 5.6.2-SNAPSHOT #907

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> update 5.5.3-SNAPSHOT #909

pom.xml
=> set source to maven-javadoc-plugin #911

pom.xml
=> [5.6.x] set source to maven-javadoc-plugin #911

.gitignore
Please review #919 .
Removed unnecessary settings from gitignore.
=> Remove unnecessary settings from gitignore #919

.gitignore
(cherry picked from commit 22a2d6d76f7f50f88442645a726e2d731d54ec29)
Please review #921 .
Removed unnecessary settings from gitignore.
=> [5.6.x]Remove unnecessary settings from gitignore #919

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> update to 5.8.0-SNAPSHOT. #932

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> update to 5.6.3-SNAPSHOT. #934

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
Please review #892 
See https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/892#issuecomment-893224390
Modified each pom.xml to match multi-blank.
=> aligned plugin settings to blank project #892

.travis.yml
Please review #941 
Added a command to check license headers in .travis.yml, similar to the comments below.
https://github.com/terasolunaorg/terasoluna-gfw/pull/1090#issuecomment-897361409
=> check license header in travis #941

pom.xml
Please review #941
See: https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/941#issuecomment-906922589
I executed `mvn license:check` and confirmed the operation.
=> fix license-maven-plugin setteing #941

.travis.yml, pom.xml
=> [5.7.x] fix license-maven-plugin setteing #941

pom.xml
=> Match postgresql and ojdbc versions with Spring Boot #953

pom.xml
(cherry picked from commit 4dc2c14548fcae2359fe8bcc769f6b55aa404385)
Please review #955
=> Match postgresql and ojdbc versions with Spring Boot #955

README.md, terasoluna-gfw-functionaltest-selenium/src/test/resources/wdm.properties
=> geckodriver version upgrade #931

terasoluna-gfw-functionaltest-env/configs/tomcat9-oracle/resources/logback.xml, terasoluna-gfw-functionaltest-env/configs/tomcat9-postgresql/resources/logback.xml, terasoluna-gfw-functionaltest-env/configs/weblogic-oracle/resources/logback.xml, terasoluna-gfw-functionaltest-env/src/main/resources/logback.xml
=> changed log format #964

terasoluna-gfw-functionaltest-env/configs/tomcat9-oracle/resources/logback.xml, terasoluna-gfw-functionaltest-env/configs/tomcat9-postgresql/resources/logback.xml, terasoluna-gfw-functionaltest-env/configs/weblogic-oracle/resources/logback.xml, terasoluna-gfw-functionaltest-env/src/main/resources/logback.xml
(cherry picked from commit 142187430f9b30ca90220db30129d2e6bdafc698)
Please review #966
=> [5.7.x] changed log format #964

README.md
=> remove build status. #968

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> update SNAPSHOT to 5.7.2 #974

.github/ISSUE_TEMPLATE/3-backport-issue.md
=> improved backport-issue template #976

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml
=> add profile for jdk17 #937

terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/date/DateController.java, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/common/include.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/date/dateTimeDisplay.jsp
=> Remove Joda-Time tag library. #991

pom.xml, terasoluna-gfw-functionaltest-selenium/src/test/resources/wdm.properties
=> Updated library and plugin version for 5.7.2 #996

terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-security.xml
=> fixed FilterSecurityInterceptor setting #998

pom.xml
Please review https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/996#issuecomment-1427651011 .
=> revert to surefire version #996

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-domain/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-infra.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/queryescape/QueryEscapeTest.java
=> update libraries and plugins for 5.8.0

terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-domain/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-infra.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/queryescape/QueryEscapeTest.java
Please review https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/996#issuecomment-1433985039 .
=> remove db2 settings #996

terasoluna-gfw-functionaltest-domain/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-domain.xml, terasoluna-gfw-functionaltest-domain/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-joda.xml, terasoluna-gfw-functionaltest-domain/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-jsr310.xml, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/time/DateAndTimeController.java, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/common/include.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/time/dateAndTimeDisplay.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/time/index.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/welcome/index.jsp
Please review #993 
No selenium code has been created yet. We will create it after the next fiscal year.
=> Create a Controller and View using ClockFactory #993

pom.xml, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/WebDriverManagerFactoryBean.java
Please review https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/996#issuecomment-1445613810 .
=> [5.7.x]update webdrivermanager

eclipse/formatter.xml, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/time/DateAndTimeController.java
Please review #1006
- Exported formatter.xml from STS4.17.1
- run `mvn formatter:format`
=> update fomratter #1006

terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/string/CustomFullHalf.java
Please review #1011
- CustomFullHalf.java
- Fixed full-width spaces to be escaped.
=> corrected SonarQube point #1011

terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/string/CustomFullHalf.java
(cherry picked from commit 13d56ad857523a7976ed70b066dc7b682bdc79af)
Please review #1013
=> [5.7.x] corrected SonarQube point #1011

README.md
=> README update #1015

README.md
=> README update #1017

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> update SNAPSHOT to 5.8.1. #1019

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingController.java, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc.xml
Please review #1024.
relates to [TSF4J5-2481](https://terasolunaorg.atlassian.net/browse/TSF4J5-2481?focusedCommentId=11290)
=> system exception resolver exclusion settings

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> update 5.9.0-SNAPSHOT. #1026

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
Please review #1028 
relate to https://terasolunaorg.atlassian.net/browse/TSF4J5-2393
=> update 5.7.3-SNAPSHOT #1028

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
Please review #1030 .
https://terasolunaorg.atlassian.net/browse/TSF4J5-2393
=> update 5.8.2-SNAPSHOT #1030

terasoluna-gfw-functionaltest-env/configs/tomcat9-oracle/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/tomcat9-postgresql/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/configs/weblogic-oracle/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-env/src/main/resources/META-INF/spring/application-env.properties, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/tiles/tiles-definitions.xml, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/layout/footer.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/layout/template.jsp
=> [5.7.x]Fixes related to footer and AP server version

terasoluna-gfw-functionaltest-domain/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-infra.xml, terasoluna-gfw-functionaltest-env/configs/tomcat10-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-infra.properties, terasoluna-gfw-functionaltest-env/configs/tomcat10-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-infra.properties, terasoluna-gfw-functionaltest-env/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-infra.properties
Please review #1040 
By reverting to https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/pull/1039 provisional response, the application was confirmed to work properly.
=> removed dialect settings #1040

JavaConfig/pom.xml, XmlConfig/pom.xml
Please review #1055
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-3939
=> library version up #1055

JavaConfig/terasoluna-gfw-functionaltest-env/configs/tomcat10-oracle/resources/META-INF/web-fragment.xml, JavaConfig/terasoluna-gfw-functionaltest-env/configs/tomcat10-postgresql/resources/META-INF/web-fragment.xml, JavaConfig/terasoluna-gfw-functionaltest-env/src/main/resources/META-INF/web-fragment.xml, XmlConfig/terasoluna-gfw-functionaltest-env/configs/tomcat10-oracle/resources/META-INF/web-fragment.xml, XmlConfig/terasoluna-gfw-functionaltest-env/configs/tomcat10-postgresql/resources/META-INF/web-fragment.xml, XmlConfig/terasoluna-gfw-functionaltest-env/src/main/resources/META-INF/web-fragment.xml
Please review #1069 
relatest to https://terasolunaorg.atlassian.net/browse/TSF4J5-4130
=> fix servlet version to 6.0 #1069

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml
Please review #1073
relatest to https://terasolunaorg.atlassian.net/browse/TSF4J5-4210
=> setting jdk21 profile #1073

JavaConfig/pom.xml, JavaConfig/terasoluna-gfw-functionaltest-domain/pom.xml, JavaConfig/terasoluna-gfw-functionaltest-env/pom.xml, JavaConfig/terasoluna-gfw-functionaltest-initdb/pom.xml, JavaConfig/terasoluna-gfw-functionaltest-selenium/pom.xml, JavaConfig/terasoluna-gfw-functionaltest-web/pom.xml, XmlConfig/pom.xml, XmlConfig/terasoluna-gfw-functionaltest-domain/pom.xml, XmlConfig/terasoluna-gfw-functionaltest-env/pom.xml, XmlConfig/terasoluna-gfw-functionaltest-initdb/pom.xml, XmlConfig/terasoluna-gfw-functionaltest-selenium/pom.xml, XmlConfig/terasoluna-gfw-functionaltest-web/pom.xml
Please review #1077.
Related to https://terasolunaorg.atlassian.net/browse/TSF4J5-2492
=> update 5.10.0-SNAPSHOT. #1077

JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringSecurityConfig.java
=> fixed how AntPathRequestMatcher is implemented #1076

JavaConfig/pom.xml, JavaConfig/terasoluna-gfw-functionaltest-domain/pom.xml, JavaConfig/terasoluna-gfw-functionaltest-env/pom.xml, JavaConfig/terasoluna-gfw-functionaltest-initdb/pom.xml, JavaConfig/terasoluna-gfw-functionaltest-selenium/pom.xml, JavaConfig/terasoluna-gfw-functionaltest-web/pom.xml, XmlConfig/pom.xml, XmlConfig/terasoluna-gfw-functionaltest-domain/pom.xml, XmlConfig/terasoluna-gfw-functionaltest-env/pom.xml, XmlConfig/terasoluna-gfw-functionaltest-initdb/pom.xml, XmlConfig/terasoluna-gfw-functionaltest-selenium/pom.xml, XmlConfig/terasoluna-gfw-functionaltest-web/pom.xml
Please review #1080.
Related to https://terasolunaorg.atlassian.net/browse/TSF4J5-4377
=> [5.9.x]update 5.9.1-SNAPSHOT. #1080

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
Please review #1082.
Related to https://terasolunaorg.atlassian.net/browse/TSF4J5-4398
=> [5.7.x]update 5.7.4-SNAPSHOT. #1082

JavaConfig/terasoluna-gfw-functionaltest-env/configs/tomcat10-oracle/resources/logback.xml, JavaConfig/terasoluna-gfw-functionaltest-env/configs/tomcat10-postgresql/resources/logback.xml, JavaConfig/terasoluna-gfw-functionaltest-env/src/main/resources/logback.xml, XmlConfig/terasoluna-gfw-functionaltest-env/configs/tomcat10-oracle/resources/logback.xml, XmlConfig/terasoluna-gfw-functionaltest-env/configs/tomcat10-postgresql/resources/logback.xml, XmlConfig/terasoluna-gfw-functionaltest-env/src/main/resources/logback.xml
Please review #1084.
Related to https://terasolunaorg.atlassian.net/browse/TSF4J5-4348
=> fix logback settings #1084

JavaConfig/terasoluna-gfw-functionaltest-env/configs/tomcat10-oracle/resources/logback.xml, JavaConfig/terasoluna-gfw-functionaltest-env/configs/tomcat10-postgresql/resources/logback.xml, JavaConfig/terasoluna-gfw-functionaltest-env/src/main/resources/logback.xml, XmlConfig/terasoluna-gfw-functionaltest-env/configs/tomcat10-oracle/resources/logback.xml, XmlConfig/terasoluna-gfw-functionaltest-env/configs/tomcat10-postgresql/resources/logback.xml, XmlConfig/terasoluna-gfw-functionaltest-env/src/main/resources/logback.xml
Please review #1086
Related to https://terasolunaorg.atlassian.net/browse/TSF4J5-2896
=> update Hibernate log output settings. #1086

terasoluna-gfw-functionaltest-env/configs/tomcat9-oracle/resources/logback.xml, terasoluna-gfw-functionaltest-env/configs/tomcat9-postgresql/resources/logback.xml, terasoluna-gfw-functionaltest-env/src/main/resources/logback.xml
Please review #1088 .
related to https://terasolunaorg.atlassian.net/browse/TSF4J5-4607
=> fix logback settings #1088

terasoluna-gfw-functionaltest-env/configs/tomcat9-oracle/resources/logback.xml, terasoluna-gfw-functionaltest-env/configs/tomcat9-postgresql/resources/logback.xml, terasoluna-gfw-functionaltest-env/src/main/resources/logback.xml
Please review #1090 .
related to https://terasolunaorg.atlassian.net/browse/TSF4J5-2909
=> update Hibernate log output settings. #1090

terasoluna-gfw-functionaltest-env/configs/tomcat9-oracle/resources/logback.xml, terasoluna-gfw-functionaltest-env/configs/tomcat9-postgresql/resources/logback.xml, terasoluna-gfw-functionaltest-env/src/main/resources/logback.xml
Please review https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/1090#issuecomment-2151150012
related to https://terasolunaorg.atlassian.net/browse/TSF4J5-2909
=> changed the logger class to one compatible with hibernate 5. #1090

JavaConfig/terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/ChromeDriverFactoryBean.java, JavaConfig/terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/EdgeDriverFactoryBean.java, JavaConfig/terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/FirefoxDriverFactoryBean.java, JavaConfig/terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/HeadlessWebDriverManagerFactoryBean.java, JavaConfig/terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/WebDriverManagerFactoryBean.java, JavaConfig/terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/WebDriverType.java, JavaConfig/terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/config/SeleniumContextConfig.java, JavaConfig/terasoluna-gfw-functionaltest-selenium/src/test/resources/META-INF/spring/selenium.properties, JavaConfig/terasoluna-gfw-functionaltest-selenium/src/test/resources/wdm.properties, XmlConfig/terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/ChromeDriverFactoryBean.java, XmlConfig/terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/EdgeDriverFactoryBean.java, XmlConfig/terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/FirefoxDriverFactoryBean.java, XmlConfig/terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/HeadlessWebDriverManagerFactoryBean.java, XmlConfig/terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/WebDriverManagerFactoryBean.java, XmlConfig/terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/WebDriverType.java, XmlConfig/terasoluna-gfw-functionaltest-selenium/src/test/resources/META-INF/spring/selenium.properties, XmlConfig/terasoluna-gfw-functionaltest-selenium/src/test/resources/META-INF/spring/seleniumContext.xml, XmlConfig/terasoluna-gfw-functionaltest-selenium/src/test/resources/wdm.properties
Please review #858.
relates to [TSF4J5-4627](https://terasolunaorg.atlassian.net/browse/TSF4J5-4627).
=> Make it headless compatible. #858

JavaConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/exception/CauseException.java, JavaConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/exception/SubClassException.java, JavaConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/exception/SuperClassException.java, JavaConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/exception/WrappingException.java, JavaConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/service/exceptionhandling/ExceptionHandlingService.java, JavaConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/service/exceptionhandling/ExceptionHandlingServiceImpl.java, JavaConfig/terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java, JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingController.java, JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ThrowIOExceptionFilter.java, JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ThrowIndexOutOfBoundsExceptionFilter.java, JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringMvcExceptionhandlingCheckCauseConfig.java, JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringMvcExceptionhandlingCheckSubClassConfig.java, JavaConfig/terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/exceptionhandling/index.jsp, JavaConfig/terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/web.xml, XmlConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/exception/CauseException.java, XmlConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/exception/SubClassException.java, XmlConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/exception/SuperClassException.java, XmlConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/exception/WrappingException.java, XmlConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/service/exceptionhandling/ExceptionHandlingService.java, XmlConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/service/exceptionhandling/ExceptionHandlingServiceImpl.java, XmlConfig/terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java, XmlConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingController.java, XmlConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ThrowIOExceptionFilter.java, XmlConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ThrowIndexOutOfBoundsExceptionFilter.java, XmlConfig/terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-check-cause.xml, XmlConfig/terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-check-subclass.xml, XmlConfig/terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/exceptionhandling/index.jsp, XmlConfig/terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/web.xml
Please review #1096
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-4753
=> added tests for new SystemExceptionResolver options #1096

terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/exception/CauseException.java, terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/exception/SubClassException.java, terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/exception/SuperClassException.java, terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/exception/WrappingException.java, terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/service/exceptionhandling/ExceptionHandlingService.java, terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/service/exceptionhandling/ExceptionHandlingServiceImpl.java, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingController.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ThrowIOExceptionFilter.java, terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ThrowIndexOutOfBoundsExceptionFilter.java, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-check-cause.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-check-subclass.xml, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/exceptionhandling/index.jsp, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/web.xml
Please review #1098
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-4813
=> added tests for new SystemExceptionResolver options #1098

JavaConfig/terasoluna-gfw-functionaltest-selenium/pom.xml, JavaConfig/terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/FunctionTestSupport.java, JavaConfig/terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/HtmlUnitDriverEx.java, JavaConfig/terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/config/SeleniumContextConfig.java, XmlConfig/terasoluna-gfw-functionaltest-selenium/pom.xml, XmlConfig/terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/FunctionTestSupport.java, XmlConfig/terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/webdrivers/HtmlUnitDriverEx.java, XmlConfig/terasoluna-gfw-functionaltest-selenium/src/test/resources/META-INF/spring/seleniumContext.xml
Please review #1108.
relates to [TSF4J5-4918](https://terasolunaorg.atlassian.net/browse/TSF4J5-4918).
=> Update htmlunit-driver.  #1108

docs/[Web]-Test-case-design-of-ELfunctions.adoc, terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/el/ElTest.java
Please review #1112 .
Corresponding backport of f:link modifications
JIRA
https://terasolunaorg.atlassian.net/browse/TSF4J5-4954
=> [5.7.x] Tests for f:link are missing, so corresponding tests are added. 

XmlConfig/terasoluna-gfw-functionaltest-domain/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-joda.xml, XmlConfig/terasoluna-gfw-functionaltest-domain/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-jsr310.xml, XmlConfig/terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-security.xml
Please review https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/1100#issuecomment-2304133293
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-4881
=> minor formatting corrections #1100

terasoluna-gfw-functionaltest-domain/src/test/resources/META-INF/spring/terasoluna-gfw-functionaltest-infra-mybatis.xml, terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-security.xml
Please review https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/1102#issuecomment-2311818802
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-4888
=> [5.7.x] minor formatting corrections #1102

terasoluna-gfw-functionaltest-env/configs/tomcat9-oracle/resources/META-INF/web-fragment.xml, terasoluna-gfw-functionaltest-env/configs/tomcat9-postgresql/resources/META-INF/web-fragment.xml, terasoluna-gfw-functionaltest-env/src/main/resources/META-INF/web-fragment.xml, terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/web.xml
Please review #1116 
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-5007
=> [5.7.x] Changed to Servlet 4.0. #1116

JavaConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/service/download/DownloadServiceImpl.java, XmlConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/service/download/DownloadServiceImpl.java
=> Apply Spring Boot 3.4.0-M2 #1118

JavaConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/model/I18nItemCode.java, JavaConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/model/ItemCode.java, JavaConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/model/Person.java, JavaConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/model/Todo.java, JavaConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/model/UserInfo.java, XmlConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/model/I18nItemCode.java, XmlConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/model/ItemCode.java, XmlConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/model/Person.java, XmlConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/model/Todo.java, XmlConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/model/UserInfo.java
Please review #1126
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-5352
=> change NotNull to NotEmpty #1126

JavaConfig/pom.xml, JavaConfig/terasoluna-gfw-functionaltest-domain/pom.xml, JavaConfig/terasoluna-gfw-functionaltest-env/pom.xml, JavaConfig/terasoluna-gfw-functionaltest-initdb/pom.xml, JavaConfig/terasoluna-gfw-functionaltest-selenium/pom.xml, JavaConfig/terasoluna-gfw-functionaltest-web/pom.xml, XmlConfig/pom.xml, XmlConfig/terasoluna-gfw-functionaltest-domain/pom.xml, XmlConfig/terasoluna-gfw-functionaltest-env/pom.xml, XmlConfig/terasoluna-gfw-functionaltest-initdb/pom.xml, XmlConfig/terasoluna-gfw-functionaltest-selenium/pom.xml, XmlConfig/terasoluna-gfw-functionaltest-web/pom.xml
=> add <developers> and <scm> on pom.xml #1124

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> [5.7.x] add <developers> and <scm> on pom.xml #1129

README.md
=> Modify README #1131

README.md
=> [5.7.x] Modify README #1133

JavaConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/model/I18nItemCode.java, JavaConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/model/ItemCode.java, JavaConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/model/Person.java, JavaConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/model/UserInfo.java, XmlConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/model/I18nItemCode.java, XmlConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/model/ItemCode.java, XmlConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/model/Person.java, XmlConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/model/UserInfo.java
Please review https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/1126#issuecomment-2503384407
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-5352
=> fixed NotEmpty to NotNull when using Size together #1126

terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/model/Todo.java
=> [5.7.x] change NotNull to NotEmpty #1140

README.md
=> Update Documentation #1146

README.md
=> Update Documentation #1148

README.md
=> [5.7.x] Update Documentation #1148

JavaConfig/pom.xml, XmlConfig/pom.xml
Please review #1152 .
relate to [TSF4J5-5959](https://terasolunaorg.atlassian.net/browse/TSF4J5-5959)
=> remove extra version, update jdbc version. #1152

JavaConfig/pom.xml, JavaConfig/terasoluna-gfw-functionaltest-initdb/pom.xml, XmlConfig/pom.xml, XmlConfig/terasoluna-gfw-functionaltest-domain/pom.xml, XmlConfig/terasoluna-gfw-functionaltest-initdb/pom.xml
Please review #1157 
relate to [TSF4J5-6117](https://terasolunaorg.atlassian.net/browse/TSF4J5-6117)
=> update ojdbc driver. #1157

pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml
Please review #1159 .
relate to https://terasolunaorg.atlassian.net/browse/TSF4J5-6126
=> update ojdbc driver. #1159

JavaConfig/pom.xml, JavaConfig/terasoluna-gfw-functionaltest-domain/pom.xml, JavaConfig/terasoluna-gfw-functionaltest-env/pom.xml, JavaConfig/terasoluna-gfw-functionaltest-initdb/pom.xml, JavaConfig/terasoluna-gfw-functionaltest-selenium/pom.xml, JavaConfig/terasoluna-gfw-functionaltest-web/pom.xml, XmlConfig/pom.xml, XmlConfig/terasoluna-gfw-functionaltest-domain/pom.xml, XmlConfig/terasoluna-gfw-functionaltest-env/pom.xml, XmlConfig/terasoluna-gfw-functionaltest-initdb/pom.xml, XmlConfig/terasoluna-gfw-functionaltest-selenium/pom.xml, XmlConfig/terasoluna-gfw-functionaltest-web/pom.xml
=> 5.11.0-SNAPSHOT #1162

JavaConfig/pom.xml, JavaConfig/terasoluna-gfw-functionaltest-domain/pom.xml, JavaConfig/terasoluna-gfw-functionaltest-env/pom.xml, JavaConfig/terasoluna-gfw-functionaltest-initdb/pom.xml, JavaConfig/terasoluna-gfw-functionaltest-selenium/pom.xml, JavaConfig/terasoluna-gfw-functionaltest-web/pom.xml, XmlConfig/pom.xml, XmlConfig/terasoluna-gfw-functionaltest-domain/pom.xml, XmlConfig/terasoluna-gfw-functionaltest-env/pom.xml, XmlConfig/terasoluna-gfw-functionaltest-initdb/pom.xml, XmlConfig/terasoluna-gfw-functionaltest-selenium/pom.xml, XmlConfig/terasoluna-gfw-functionaltest-web/pom.xml
=> 5.10.1-SNAPSHOT #1163

pom.xml, terasoluna-gfw-functionaltest-domain/pom.xml, terasoluna-gfw-functionaltest-env/pom.xml, terasoluna-gfw-functionaltest-initdb/pom.xml, terasoluna-gfw-functionaltest-selenium/pom.xml, terasoluna-gfw-functionaltest-web/pom.xml
=> 5.7.5-SNAPSHOT #1164

JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringMvcConfig.java, JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringMvcExceptionhandlingChangeAttributeConfig.java, JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringMvcExceptionhandlingChangeDefaultStatusCodeConfig.java, JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringMvcExceptionhandlingCheckCauseConfig.java, JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringMvcExceptionhandlingCheckSubClassConfig.java, JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringMvcExceptionhandlingExceptionloggerVariationConfig.java, JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringMvcExceptionhandlingIgnoreResultMessagesConfig.java, JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringMvcExceptionhandlingLogFormatConfig.java, JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringMvcExceptionhandlingMessageExceptionCoderesolverConfig.java, JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringMvcExceptionhandlingRedirectConfig.java
=> Modify Javadoc #1156

JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringMvcConfig.java, JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringMvcExceptionhandlingChangeAttributeConfig.java, JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringMvcExceptionhandlingChangeDefaultStatusCodeConfig.java, JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringMvcExceptionhandlingCheckCauseConfig.java, JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringMvcExceptionhandlingCheckSubClassConfig.java, JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringMvcExceptionhandlingExceptionloggerVariationConfig.java, JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringMvcExceptionhandlingIgnoreResultMessagesConfig.java, JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringMvcExceptionhandlingLogFormatConfig.java, JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringMvcExceptionhandlingMessageExceptionCoderesolverConfig.java, JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringMvcExceptionhandlingRedirectConfig.java
(cherry picked from commit 2aba2b9ed40b1b8582f045c67fbbaffa7d5f47b3)
Please review #1172.
=> [5.10.x] Modify Javadoc #1172

JavaConfig/terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/message/elementSpecified.jsp, XmlConfig/terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/message/elementSpecified.jsp
Please review #1176.
relates to [TSF4J5-6579](https://terasolunaorg.atlassian.net/browse/TSF4J5-6579).
=> typo. #1176

JavaConfig/pom.xml, XmlConfig/pom.xml
=> remove snapshot repository, #1186
