terasolunaorg/terasoluna-gfw-functionaltest

terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/service/queryescape/AbstractDatabaseMetaInfoService.java

Changed to call `OracleVersionRetriever#getVersion` only in case of Oracle #164

avoid calling oracleVersionRetriever#getVersion in case of PostgreSQL #164

---

.travis.yml
terasoluna-gfw-functionaltest-web/pom.xml

Please review #301.
The reason you have removed the dependency to env from domain is domain is not depend env's classes and dependency at all. web multi blank project as well (domain is not depend env).

add a dependency env to taglibs-standard-jstlel, and remove dependency domain to env #301

---

terasoluna-gfw-functionaltest-domain/pom.xml
terasoluna-gfw-functionaltest-env/pom.xml

Please review #425 .
- terasoluna-gfw 「[Packaging type of artifacts without java files should be pom #519](https://github.com/terasolunaorg/terasoluna-gfw/issues/519)」

Add the type in the description of the dependency #425

---

terasoluna-gfw-functionaltest-env/configs/jboss7-postgresql/webapp/WEB-INF/jboss-deployment-structure.xml

Please review #507 .
JBoss modules : org.slf4j, org.apache.commons.logging, org.hibernate.validator, javax.inject.api, javax.validation.api, org.javassist and org.jboss.logging conflict with the libraries in the war file.

exclude JBoss modules which conflict with the libraries in the war file #507

---

terasoluna-gfw-functionaltest-env/configs/jboss-postgresql/webapp/WEB-INF/jboss-deployment-structure.xml

Please review #545.
I have compared the libraries in the war file with JBoss6 modules which are read when the war file is deployed.
Then, I found that javax.inject.api module is conflicted and a few settings are unnecessary (concretely, org.apache.commons.logging, javax.servlet.api, javax.servlet.jsp.api modules should be removed in jboss-deployment-structure.xml file).

optimize jboss6 module structure #545

---

terasoluna-gfw-functionaltest-env/configs/jboss-postgresql/webapp/WEB-INF/jboss-deployment-structure.xml

Please review #584 .
The liberaries structure in the war file in 5.2.x is most of same as it in 5.3.x.
Therefore, no need to change jboss-deployment-structure.xml file.
I tested this branch and verified the result was ok.
cherry picked from commit 45da47b7db605c08d951ed42a9d63a58b4e0050d

[5.2.x] optimize jboss6 module structure #584

---

terasoluna-gfw-functionaltest-env/configs/jboss-postgresql/webapp/WEB-INF/jboss-deployment-structure.xml

Please review #584.
The liberaries structure in the war file in 5.1.x is also most of same as one in 5.3.x.
Therefore, no need to change jboss-deployment-structure.xml file.
I tested this branch and verified the result was ok.
(cherry picked from commit 45da47b7db605c08d951ed42a9d63a58b4e0050d)

[5.1.x] optimize jboss6 module structure #584

---

terasoluna-gfw-functionaltest-env/configs/jboss-postgresql/webapp/WEB-INF/jboss-deployment-structure.xml

Please review #584.
The liberaries structure in the war file in 5.0.x is also most of same as one in 5.3.x.
Therefore, no need to change jboss-deployment-structure.xml file.
I tested this branch and verified the result was ok.
(cherry picked from commit 45da47b7db605c08d951ed42a9d63a58b4e0050d)

[5.0.x] optimize jboss6 module structure #584

---

terasoluna-gfw-functionaltest-env/configs/interstage11-oracle/resources/META-INF/spring/application-env.properties
terasoluna-gfw-functionaltest-env/configs/jboss-postgresql/resources/META-INF/spring/application-env.properties
terasoluna-gfw-functionaltest-env/configs/jboss7-postgresql/resources/META-INF/spring/application-env.properties
terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/resources/META-INF/spring/application-env.properties
terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/resources/META-INF/spring/application-env.properties
terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/resources/META-INF/spring/application-env.properties
terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/resources/META-INF/spring/application-env.properties
terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/resources/META-INF/spring/application-env.properties
terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/resources/META-INF/spring/application-env.properties
terasoluna-gfw-functionaltest-env/configs/weblogic-oracle/resources/META-INF/spring/application-env.properties
terasoluna-gfw-functionaltest-env/configs/webotx-oracle/resources/META-INF/spring/application-env.properties
terasoluna-gfw-functionaltest-env/configs/webspherelp-db2/resources/META-INF/spring/application-env.properties
terasoluna-gfw-functionaltest-env/configs/webspheretr-db2/resources/META-INF/spring/application-env.properties
terasoluna-gfw-functionaltest-env/src/main/resources/META-INF/spring/application-env.properties
terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/ApServerName.java
terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/WebDriverOperations.java
terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/logging/LoggingTest.java
terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/redirect/RedirectTest.java
terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/PropertySourceConfig.java
terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/applicationContext.xml
terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/layout/template.jsp

The contents of the 3 commits in this PR are as follows
----
1st commit
I applied the mechanism of spring-functionaltest application (recognize application server) at c184140a3f801ac4874bccb907ff6a0dee494be9 commit.
2nd commit
As a result of applying the spring-functionaltest application mechanism, errors occured in `LoggingTest.java` of `test01_01_createDefaultXTrackMDC` and `test01_02_createCustomXTrackMDC`.
Those above errors are due to getting the AP server name instead of MDC as a result of trying to acquire MDC by using the p element.
So I changed the method of element(MDC) acquisition from p to id at 736a92a4f10a5f4f7167e259ef6e952761dd4eb0 commit.
I checked the [test item table page](https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/wiki/%5BWeb%5D- …

recognize ap server #605

---

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java

Remove ignore annotation at [ExceptionHandlingTest#test02_01_useCaseControllerHandling](https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/blob/master/terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/exceptionhandling/ExceptionHandlingTest.java#L69).
At the time of #80 , because behavior of each AP server differently, Ignore annotation was attached.
However, at the present time, there is no differences among AP server.
Note:
This test case was ignored. Because it does not have to be tested with HttpStatusCode 100(Continue). (Currently tested with 4 HttpStatusCode from 200 to 500)
However, this does not mean that the test case of HttpStatusCode 100 is useless.

remove @ignore at ExceptionHandlingTest #605

---

terasoluna-gfw-functionaltest-env/configs/resin-oracle/resources/META-INF/spring/application-env.properties
terasoluna-gfw-functionaltest-env/configs/resin-postgresql/resources/META-INF/spring/application-env.properties
terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/resources/META-INF/spring/application-env.properties
terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/resources/META-INF/spring/application-env.properties
terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/resources/META-INF/spring/application-env.properties
terasoluna-gfw-functionaltest-env/configs/weblogic-oracle/resources/META-INF/spring/application-env.properties
terasoluna-gfw-functionaltest-env/src/main/resources/META-INF/spring/application-env.properties
terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/ApServerName.java
terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/WebDriverOperations.java
terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/logging/LoggingTest.java
terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/PropertySourceConfig.java
terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/applicationContext.xml
terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/layout/template.jsp

This PR is backport for 1.0.x .
In addition to `cherry-pick` , I add `<span id>` tag in template.jsp at 547a58b850db2ff0e1be7073858d683da0abd601 commit .
Because in 1.0.x branch , X-Track does not have `<span id>` tag .
I checked above change does not affect any test cases .

[1.0.x]recognize ap server #605

---

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/validation/ValidationTest.java
terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/validation/ValidationController.java
terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/validation/ValidationForm.java
terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/views/validation/compare.jsp

(cherry picked from commit 499dcf998529b3eb0121e723b7dd27db32d3d55d)
Please review #647.  Backport for 5.3.x

[5.3.x]Add test for NOT_EQUAL using @Compare #647

---

.travis.yml

This PR is backport for 5.3.x .

[5.3.x] add firefox version at .travis.yml #655

---

.travis.yml

This PR is backport for 5.2.x .

[5.2.x] add firefox version at .travis.yml #655

---

.travis.yml

This PR is backport for 5.1.x .

[5.1.x] add firefox version at .travis.yml #655

---

.travis.yml

This PR is backport for 5.0.x .

[5.0.x] add firefox version at .travis.yml #655

---

.travis.yml

This PR is backport for 1.0.x .

[1.0.x] add firefox version at .travis.yml #655

---

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/WaitWebDriverEventListener.java

Please review #740 .
Because exception handling was not applied to wait.until (), 
problem occurred when TimeoutException occurred.
Therefore, implemented exception handling.

add Exception handling #740

---

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/PageSource.java
terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/queryescape/QueryEscapeTest.java
terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/el/ElMapOfSimpleValueDefaultTrimController.java
terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/message/MessageController.java
terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/pagination/PaginationController.java
terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/transactiontoken/TransactionTokenFlow1Controller.java

Please review #788 .
Cherry-picked from commit https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/commit/01cb002fac134c5ff08cfb07ceb2c8cc503268a0
The second commit is related to PageRequest.
In 5.4.x, `new PageRequest` is recommended API, so it was restored.

[5.4.x] resolve deprecated api #788

---

.travis.yml

Cherry-pick from commit ff85fda0cf781a8a4f8946c735eda3889831b585 .
Added setting to use openjdk7.

[5.4.x] Suppress log output #819 Fix Travis CI environment for Trusty #814

---

.travis.yml

Cherry-pick from commit cc645bece2c542f9248a563d56196057a45483bf, 02e8e241a710ba8a5beda185b2f6b007e2fcdf23 .

[5.3.x] Suppress log output #819 Fix Travis CI environment for Trusty #814

---

.travis.yml

Cherry-pick from commit a407f0465f99cb91ee9ca482c370f4709550677b, 309bc431f213007334bc13aa5ae66bfd161ef799.

[5.2.x] Suppress log output #819 Fix Travis CI environment for Trusty #814

---

.travis.yml

Cherry-pick from commit 211fd7f27bf16bbdf368120a28fc8fa1ca67bf6e, a72b331f8c0521743c6965ea5c3b8b57c417c3cf .

[5.1.x] Suppress log output #819 Fix Travis CI environment for Trusty #814

---

.travis.yml

Cherry-pick from commit 9607ff9b511fef8682bdcfd652a9625899303de8, 85e13c6e3ef9a8f6aa860bde880606a496966d31.

[5.0.x] Suppress log output #819 Fix Travis CI environment for Trusty #814

---

.travis.yml

Cherry-pick from commit e9f3c37da310c8f935f9221321c341f0cbd2429a, 8e6ccd8bd9a3ed8f03fbcd0d689540ee066af525.

[1.0.x] Suppress log output #819 Fix Travis CI environment for Trusty #814

---

terasoluna-gfw-functionaltest-env/configs/interstage11-oracle/resources/logback.xml
terasoluna-gfw-functionaltest-env/configs/jboss-postgresql/resources/logback.xml
terasoluna-gfw-functionaltest-env/configs/jboss7-postgresql/resources/logback.xml
terasoluna-gfw-functionaltest-env/configs/tomcat-oracle/resources/logback.xml
terasoluna-gfw-functionaltest-env/configs/tomcat-postgresql/resources/logback.xml
terasoluna-gfw-functionaltest-env/configs/tomcat8-oracle/resources/logback.xml
terasoluna-gfw-functionaltest-env/configs/tomcat8-postgresql/resources/logback.xml
terasoluna-gfw-functionaltest-env/configs/tomcat85-oracle/resources/logback.xml
terasoluna-gfw-functionaltest-env/configs/tomcat85-postgresql/resources/logback.xml
terasoluna-gfw-functionaltest-env/configs/tomcat9-oracle/resources/logback.xml
terasoluna-gfw-functionaltest-env/configs/tomcat9-postgresql/resources/logback.xml
terasoluna-gfw-functionaltest-env/configs/weblogic-oracle/resources/logback.xml
terasoluna-gfw-functionaltest-env/configs/webotx-oracle/resources/logback.xml
terasoluna-gfw-functionaltest-env/configs/webspherelp-db2/resources/logback.xml
terasoluna-gfw-functionaltest-env/src/main/resources/logback.xml

Please review #837.
See https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/issues/837#issuecomment-591774990
* add settings
* org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping
* org.springframework.jdbc.core.JdbcTemplate
* org.hibernate.SQL
* org.hibernate.type
* remove settings
* org.springframework.jdbc.datasource
* org.springframework.orm.jpa
* org.springframework.transaction
* jdbc.sqltiming (forget to erase)
It is determined that there is no problem because the logs output with the excluded settings are as follows.
(`org.springframework.transaction` is not logged in test execution)
``` java
level:DEBUG	logger:o.springframework.orm.jpa.JpaTransactionManager 	message:Found thread-bound EntityManager [SessionImpl(2063178510<open>)] for JPA …
```

fix logback settings #837

---

terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/domain/DBLogCleaner.java
terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/FunctionTestSupport.java
terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/transactiontoken/TransactionTokenTest.java

Please review #852 .
Confirmed that the compilation was successful.
Since Logger object is not defined in [TransactionTokenTest.java](https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/blob/master/terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/transactiontoken/TransactionTokenTest.java), the next dependent Logger object was referenced.
- https://github.com/spring-projects/spring-framework/blob/v5.2.3.RELEASE/spring-context/src/main/java/org/springframework/context/support/ApplicationObjectSupport.java#L52
Since the Logger object to be referenced is the one of FunctionTestSupport.java by correcting the object name, a compilation error occurs because it is private.
Defined because it is correct to define Logger object in …

fix logger name #852

---

terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/web.xml

Please review #913.
Confirmation
Confirmed that the addition of the setting causes the output of the log on destroy, which was not output before the modification.

Added a setting to output logs during destroy #913

---

terasoluna-gfw-functionaltest-web/src/main/webapp/WEB-INF/web.xml

(cherry picked from commit 26f912460dfcfbfd453ba0f6459bee258cbc380b)
Please review #917.
Confirmation
Confirmed that the addition of the setting causes the output of the log on destroy, which was not output before the modification.

[5.6.x]Added a setting to output logs during destroy #913

---

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/pagination/PaginationTest.java

Please review #924
Confirmation method：
- Confirm that PaginationTest succeeds in local and test04_03_maxDisplayCountSpecified is skipped
-  Confirm PaginationTest succeeds and test04_03_maxDisplayCountSpecified is skipped in weblogic of GitLab

added Ignore to test04_03_maxDisplayCountSpecified #924

---

terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/pagination/PaginationTest.java

(cherry picked from commit 4fd71dfa1fcdf7e65524109cb97eb224aa35cb5a)
Please review #929 
Confirmation method：
- Confirm that PaginationTest succeeds in local and test04_03_maxDisplayCountSpecified is skipped
-  Confirm PaginationTest succeeds and test04_03_maxDisplayCountSpecified is skipped in weblogic of GitLab

[5.6.x] added Ignore to test04_03_maxDisplayCountSpecified #924

---

pom.xml
terasoluna-gfw-functionaltest-initdb/pom.xml

Please review #892.
Confirmation is done with maven 3.8.1.
The changes other than the version upgrade are as follows:
- The `com.google.code:maven-license-plugin` has been changed to `com.mycila:license-maven-plugin` as in https://github.com/terasolunaorg/terasoluna-gfw/issues/600.
- The following plugins are not currently in use and have been removed.
- maven-failsafe-plugin
- build-helper-maven-plugin
- Changed the version setting of sql-maven-plugin to be described in initdb so that it is similar to multi-blank.
https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/pull/893/commits/3bdcaf1e8dedd18b187685d9cd5e1b57292c079a
- Fixed the variable name of the plugin version to be `groupId.artifactId.pugin.version`.
https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/pull/ …

update the maven plugin #892

---

pom.xml
terasoluna-gfw-functionaltest-domain/pom.xml
terasoluna-gfw-functionaltest-env/pom.xml
terasoluna-gfw-functionaltest-initdb/pom.xml
terasoluna-gfw-functionaltest-selenium/pom.xml
terasoluna-gfw-functionaltest-web/pom.xml

Please review #938 
The changes other than the version upgrade are as follows:
- The `com.google.code:maven-license-plugin` has been changed to `com.mycila:license-maven-plugin` as in https://github.com/terasolunaorg/terasoluna-gfw/issues/600.
- The following plugins are not currently in use and have been removed.
- maven-failsafe-plugin
- build-helper-maven-plugin
- Changed the version setting of sql-maven-plugin to be described in initdb so that it is similar to multi-blank.
- Fixed the variable name of the plugin version to be `groupId.artifactId.pugin.version`.
- cargo-maven2-plugin has been renamed to cargo-maven3-plugin since 1.9.0
https://codehaus-cargo.github.io/cargo/Maven+3+Plugin.html

[5.7.x] update the maven plugin #892

---

eclipse/formatter.xml
terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/queryescape/QueryEscapeTest.java

Please review #943
I ran `mvn fomratter:format` to format it.
formatter.xml uses the one generated in https://github.com/terasolunaorg/terasoluna-gfw/pull/1092.

modify formatter.xml and format source code #943

---

pom.xml
terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/FunctionTestSupport.java
terasoluna-gfw-functionaltest-selenium/src/test/java/org/terasoluna/gfw/functionaltest/app/WebDriverOperations.java
terasoluna-gfw-functionaltest-selenium/src/test/resources/META-INF/spring/selenium.properties
terasoluna-gfw-functionaltest-web/pom.xml

Please review #981,#982
See https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/pull/984#pullrequestreview-1072288500
relate to [TSF4J5-1301](https://terasolunaorg.atlassian.net/browse/TSF4J5-1301)([TSF4J5-1289](https://terasolunaorg.atlassian.net/browse/TSF4J5-1289)),[TSF4J5-1365](https://terasolunaorg.atlassian.net/browse/TSF4J5-1365),
https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/pull/984#discussion_r945475729
16ad9f9d0a10b10f96c8e6a31e426eb18d66af96
Since `logback-classic-db` is defined by domain, it has been deleted from the web.
https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/pull/984#discussion_r945468141
01cb6fd6091321d21e9ecd2e52918755fc0d26e6
Changed `logback-classic-db.version` to `logback-db.version`. …

fixed duration and logback-classic-db

---

.gitignore
pom.xml
terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/applicationContext.xml

Please review #988
In accordance with the blank project, the pom.xml contains the `maven-compiler-plugin` configuration, but it is commented out because MapStruct is not used.

migrated dozer to mapstruct #988

---

eclipse/formatter.xml

(cherry picked from commit db94b3807cbb6fa4f351720170ad58df3faa1227)
Please review #1006 
- `Ctrl + O` on STS (no change)
- Exported formatter.xml from STS4.17.1
- run `mvn formatter:format` (no change)

update formatter.xml #1006

---

terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-security.xml

Please review #1021 .
> Set `request-matcher="ant"` for all `sec:http` tags.
No fix required because it is defined in the existing source code.
https://github.com/terasolunaorg/terasoluna-gfw-functionaltest/blob/29d6aebda9772dbb83651477623d401bf209ccca/terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-security.xml#L9

remove mvcHandlerMappingIntrospector #1021

---

terasoluna-gfw-functionaltest-domain/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-infra.xml
terasoluna-gfw-functionaltest-env/configs/tomcat10-oracle/resources/META-INF/spring/terasoluna-gfw-functionaltest-infra.properties
terasoluna-gfw-functionaltest-env/configs/tomcat10-postgresql/resources/META-INF/spring/terasoluna-gfw-functionaltest-infra.properties
terasoluna-gfw-functionaltest-env/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-infra.properties

Please review #1038 
When using PostgreSQL, the dialect class used for `HibernateJpaVendorAdapter` is `org.hibernate.dialect.PostgreSQL95Dialect`, which has been removed since hibernate 6.2.
This problem has been fixed in the following commit, so we will revert this fix the next time we upgrade the Spring Boot version and see if it works.
https://github.com/spring-projects/spring-framework/commit/4c8f1910c82c340135082f3947f7dd9b611d6849

modified to specify dialect for each DB #1038

---

terasoluna-gfw-functionaltest-domain/src/test/resources/test-context.xml
terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/applicationContext.xml
terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-change-attribute.xml
terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-change-default-status-code.xml
terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-exceptionlogger-variation.xml
terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-ignore-result-messages.xml
terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-log-format.xml
terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-message-exception-coderesolver.xml
terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc-exceptionhandling-redirect.xml
terasoluna-gfw-functionaltest-web/src/main/resources/META-INF/spring/spring-mvc.xml

Please review #1044 .
Since the backport will be a version where JavaConfig doesn't exist yet, we only reflected the XML modifications.
JIRA
https://terasolunaorg.atlassian.net/browse/TSF4J5-3072

Backport:Added aop:aspectj-autoproxy according to JavaConfig definition. #1044

---

JavaConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/config/app/TerasolunaGfwFunctionaltestDomainConfig.java
JavaConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/config/app/TerasolunaGfwFunctionaltestInfraConfig.java
JavaConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/config/app/TerasolunaGfwFunctionaltestJodaConfig.java
JavaConfig/terasoluna-gfw-functionaltest-domain/src/main/java/org/terasoluna/gfw/functionaltest/config/app/TerasolunaGfwFunctionaltestJsr310Config.java
JavaConfig/terasoluna-gfw-functionaltest-env/src/main/java/org/terasoluna/gfw/functionaltest/config/app/TerasolunaGfwFunctionaltestEnvConfig.java
JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/date/DateController.java
JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/el/ElController.java
JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringMvcConfig.java
JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringMvcExceptionhandlingChangeAttributeConfig.java
JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringMvcExceptionhandlingChangeDefaultStatusCodeConfig.java
JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringMvcExceptionhandlingExceptionloggerVariationConfig.java
JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringMvcExceptionhandlingIgnoreResultMessagesConfig.java
JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringMvcExceptionhandlingLogFormatConfig.java
JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringMvcExceptionhandlingMessageExceptionCoderesolverConfig.java
JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringMvcExceptionhandlingRedirectConfig.java
JavaConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/config/web/SpringSecurityConfig.java
XmlConfig/terasoluna-gfw-functionaltest-env/src/main/resources/META-INF/spring/terasoluna-gfw-functionaltest-env.xml
XmlConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/date/DateController.java
XmlConfig/terasoluna-gfw-functionaltest-web/src/main/java/org/terasoluna/gfw/functionaltest/app/el/ElController.java

Please review #1053 
related to https://terasolunaorg.atlassian.net/browse/TSF4J5-3811
- In JavaConfig, modified to use `@Qualifier` to specify the name of a bean when a bean with the same type exists in the definition.
- Modified to make the name explicit when using `@RequestParam`.
- Deprecated methods fixed.
- `@SuppressWarnings` was given to classes using JodaTime.

update boot to 3.2.0 #1053

---

pom.xml

Please review #1059 
relates to https://terasolunaorg.atlassian.net/browse/TSF4J5-3951
For httpclient5, the version managed by Spring-boot conflicts with the version on which webdrivermanager depends, so the version is set in pom.xml.

[5.7.x] library version up #1059
